#!/usr/bin/env python3
"""Generate tests/data/exp_dd_reference.txt -- oracle for the dd exp kernel.

The kernel is internal (no public API), so its test drives it directly; this
file is the correctly-rounded oracle it is measured against. Unlike the erf and
erfc reference sets, each entry carries the value as a DOUBLE-DOUBLE, because
the point of exp_dd is to be right well past the last bit of a double:

    x_hi x_lo  exp_hi exp_lo        (four hex doubles per line)

exp_hi = RN(exp(x)), exp_lo = RN(exp(x) - exp_hi). x is itself a dd pair so the
set can exercise the way erfc calls the kernel (an exactly split a^2), not just
the x_lo = 0 case.

Point selection targets the places the method can break:
  * every table entry j = k mod 128, at both ends of the reduced interval,
  * both saturation edges (overflow above 709.78, flush-to-zero below -745.2)
    and the whole subnormal-result band between -745.2 and -708.4,
  * arguments with |x| large enough that a sloppy reduction shows (|x| ~ 700),
  * exactly split a^2 for a in [6, 28] -- the erfc tail's own arguments,
  * zero, tiny, and denormal-adjacent x.

Usage:
    python3 tools/gen_exp_dd_reference.py > tests/data/exp_dd_reference.txt
"""

import random
import sys

import mpmath as mp

mp.mp.dps = 60

N = 128
LN2_OVER_N = mp.log(2) / N


def split(v):
    """mpf -> (hi, lo) doubles with hi = RN(v)."""
    hi = float(v)
    lo = float(v - mp.mpf(hi))
    return hi, lo


def emit(rows, xh, xl=0.0):
    if not (abs(xh) <= 1100.0):
        return
    v = mp.e ** (mp.mpf(xh) + mp.mpf(xl))
    hi, lo = split(v)
    rows.append((xh, xl, hi, lo))


def main():
    rng = random.Random(20260725)
    rows = []

    # Zero, tiny, and the region where k = 0.
    for x in (0.0, 5e-324, 1e-300, 1e-20, 2**-30, -(2**-30), 0.002, -0.002,
              0.0027, -0.0027):
        emit(rows, x)

    # Every table slot, sampled at both edges of the reduced interval and at a
    # few octaves, so a wrong entry or a wrong j cannot hide.
    for j in range(N):
        for e in (-10, 0, 3, 9):
            centre = (e * N + j) * LN2_OVER_N
            for frac in (mp.mpf(-0.499), mp.mpf(0), mp.mpf(0.499)):
                emit(rows, float(centre + frac * LN2_OVER_N))

    # Uniform sweep of the finite range.
    for _ in range(3000):
        emit(rows, rng.uniform(-745.0, 709.7))

    # Large |x|, where an inexact reduction is amplified the most.
    for _ in range(600):
        emit(rows, rng.uniform(690.0, 709.78))
        emit(rows, rng.uniform(-709.0, -690.0))

    # Subnormal-result band and the flush-to-zero edge.
    for _ in range(800):
        emit(rows, rng.uniform(-745.2, -708.3))
    for x in (-708.396418532264, -745.1332191019411, -745.2, -744.0, -740.0):
        emit(rows, x)

    # Overflow edge (results above ~709.7827 are +inf and carry no information,
    # so stay just inside it).
    for _ in range(200):
        emit(rows, rng.uniform(709.7, 709.782712893384))

    # erfc's own arguments: x = -(a*a) split exactly, a in [6, 28].
    for _ in range(900):
        a = rng.uniform(6.0, 28.0)
        sq = mp.mpf(a) * mp.mpf(a)
        hi = float(sq)
        lo = float(sq - mp.mpf(hi))
        emit(rows, -hi, -lo)

    rows.sort(key=lambda t: t[0])
    print(f"# exp reference: x_hi x_lo exp_hi exp_lo (hex doubles), {len(rows)} points")
    print("# generated by tools/gen_exp_dd_reference.py; mpmath oracle at 60 dps")
    for xh, xl, hi, lo in rows:
        print(f"{xh.hex()} {xl.hex()} {hi.hex()} {lo.hex()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
