#!/usr/bin/env python3
"""Generate src/erfc_tail_data.h -- polynomial fits for erfc's tail region.

For a > 6, erfc(a) = e^{-a^2} * G(u) * u with u = 1/a and
G(u) = a * e^{a^2} * erfc(a). G is smooth and slowly varying on compact
u-intervals bounded away from u = 0 (the essential singularity), so
Chebyshev interpolation converges geometrically. Fitting in u (not
t = 1/a^2) keeps the Bernstein-ellipse parameter ~8 per interval, which
both keeps degrees ~20 and keeps the Chebyshev->monomial conversion
well-conditioned (coefficients stay O(1)).

Intervals: a in [6,10], [10,17], [17,28]. All fits are padded to one
uniform degree so the kernel can select coefficients per lane and run a
single Horner pass. Polynomials are in the normalized variable
s = u*scale + shift, s in [-1,1].

mpmath is an oracle for VALUES of erfc/exp only; the fit itself is plain
Chebyshev interpolation (own implementation below).

Usage:
    python3 tools/gen_erfc_tail_poly.py > src/erfc_tail_data.h
"""

import random
import sys

import mpmath as mp

mp.mp.dps = 60

INTERVALS = [(6.0, 10.0), (10.0, 17.0), (17.0, 28.0)]
N_NODES = 129
TAIL_CUT = mp.mpf("1e-19")   # truncate Chebyshev series below this
# Dense-verification gate, in RELATIVE error of the double-Horner evaluation.
# The floor is evaluation rounding (~1 ULP), not fit error -- the mpmath-side
# fit residual is far smaller. ~1.5 ULP allowance.
REL_TARGET = 2.5e-16


def G(a):
    a = mp.mpf(a)
    return a * mp.e ** (a * a) * mp.erfc(a)


def cheb_coeffs(f, lo, hi, n_nodes):
    c = (mp.mpf(lo) + mp.mpf(hi)) / 2
    h = (mp.mpf(hi) - mp.mpf(lo)) / 2
    nodes = [mp.cos(mp.pi * (j + mp.mpf(1) / 2) / n_nodes) for j in range(n_nodes)]
    vals = [f(c + h * s) for s in nodes]
    coeffs = []
    for k in range(n_nodes):
        acc = mp.mpf(0)
        for j in range(n_nodes):
            acc += vals[j] * mp.cos(mp.pi * k * (j + mp.mpf(1) / 2) / n_nodes)
        a_k = 2 * acc / n_nodes
        coeffs.append(a_k / 2 if k == 0 else a_k)
    return coeffs, c, h


def truncate(coeffs):
    deg = len(coeffs) - 1
    while deg > 0 and abs(coeffs[deg]) < TAIL_CUT:
        deg -= 1
    return coeffs[: deg + 1]


def cheb_to_monomial(coeffs):
    """Sum a_k T_k(s) as monomial coefficients in s (ascending)."""
    t_prev = [mp.mpf(1)]            # T_0
    t_cur = [mp.mpf(0), mp.mpf(1)]  # T_1
    mono = [mp.mpf(0)] * len(coeffs)

    def add(poly, w):
        for i, p in enumerate(poly):
            mono[i] += w * p

    add(t_prev, coeffs[0])
    if len(coeffs) > 1:
        add(t_cur, coeffs[1])
    for k in range(2, len(coeffs)):
        # T_{k} = 2s*T_{k-1} - T_{k-2}
        t_next = [mp.mpf(0)] + [2 * x for x in t_cur]
        for i, x in enumerate(t_prev):
            t_next[i] -= x
        add(t_next, coeffs[k])
        t_prev, t_cur = t_cur, t_next
    return mono


def horner_double(mono_d, s):
    acc = 0.0
    for cf in reversed(mono_d):
        acc = acc * s + cf
    return acc


def main():
    rng = random.Random(20260721)
    fits = []
    max_deg = 0
    for lo, hi in INTERVALS:
        ulo, uhi = 1.0 / hi, 1.0 / lo
        coeffs, c, h = cheb_coeffs(lambda u: G(1 / u), ulo, uhi, N_NODES)
        coeffs = truncate(coeffs)
        mono = cheb_to_monomial(coeffs)
        mono_d = [float(x) for x in mono]
        scale = float(1 / h)
        shift = float(-c / h)

        worst = 0.0
        for _ in range(3000):
            u = rng.uniform(ulo, uhi)
            s = u * scale + shift
            got = horner_double(mono_d, s)
            want = G(1.0 / u)
            rel = abs((mp.mpf(got) - want) / want)
            worst = max(worst, float(rel))
        deg = len(mono_d) - 1
        print(f"a in [{lo},{hi}]: degree {deg}, dense max rel err {worst:.2e}",
              file=sys.stderr)
        if worst > REL_TARGET:
            print(f"FAILED: exceeds {REL_TARGET:g}", file=sys.stderr)
            return 1
        fits.append((lo, hi, scale, shift, mono_d))
        max_deg = max(max_deg, deg)

    n_coef = max_deg + 1
    print("// Auto-generated by tools/gen_erfc_tail_poly.py. DO NOT EDIT.")
    print("// Polynomial fits of G(u) = a*e^{a^2}*erfc(a), u = 1/a, in the")
    print("// normalized variable s = u*kErfcTailScale[i] + kErfcTailShift[i].")
    print("// Coefficients ascending; all intervals zero-padded to one degree")
    print("// so the kernel selects per-lane and runs a single Horner pass.")
    print("// Interval bounds (in a): [6,10], [10,17], [17,28].")
    print("#ifndef CORVUS_ERFC_TAIL_DATA_H_")
    print("#define CORVUS_ERFC_TAIL_DATA_H_")
    print()
    print("namespace corvus::detail {")
    print()
    print(f"inline constexpr int kErfcTailNCoef = {n_coef};")
    print("inline constexpr double kErfcTailBound1 = 10.0;  // interval 0/1 split")
    print("inline constexpr double kErfcTailBound2 = 17.0;  // interval 1/2 split")
    print("inline constexpr double kErfcTailScale[3] = {")
    for _, _, scale, _, _ in fits:
        print(f"    {float.hex(scale)},")
    print("};")
    print("inline constexpr double kErfcTailShift[3] = {")
    for _, _, _, shift, _ in fits:
        print(f"    {float.hex(shift)},")
    print("};")
    print(f"inline constexpr double kErfcTailCoef[3][{n_coef}] = {{")
    for lo, hi, _, _, mono_d in fits:
        padded = mono_d + [0.0] * (n_coef - len(mono_d))
        print(f"    {{  // a in [{lo}, {hi}]")
        for cf in padded:
            print(f"        {float.hex(cf)},")
        print("    },")
    print("};")
    print()
    print("}  // namespace corvus::detail")
    print()
    print("#endif  // CORVUS_ERFC_TAIL_DATA_H_")
    return 0


if __name__ == "__main__":
    sys.exit(main())
