#!/usr/bin/env python3
"""Generate tests/data/log_dd_reference.txt -- oracle for the dd log kernel.

Same shape as the exp reference set (see tools/gen_exp_dd_reference.py):

    x_hi x_lo  log_hi log_lo        (four hex doubles per line)

log_hi = RN(log(x)), log_lo = RN(log(x) - log_hi). x is a dd pair so the set
exercises the dd-input overload as well as the plain-double one.

Point selection targets where the method can break:
  * every slot j = top 7 mantissa bits, at both slot edges,
  * BOTH SIDES of x = 1 down to the adjacent doubles -- the case the centred
    mantissa and the exact (R, L) = (1, 0) slots exist for, and the one an
    uncentred table gets catastrophically wrong,
  * the halving threshold 1 + 53/128, either side,
  * the extremes of the normal range (x ~ 2^-1022 and ~2^1023), where the
    k*ln2 term dominates and its dd split has to hold up,
  * exact powers of two, where log must come out as k*ln2 with no polynomial
    contribution at all.

Usage:
    python3 tools/gen_log_dd_reference.py > tests/data/log_dd_reference.txt
"""

import math
import random
import struct
import sys

import mpmath as mp

mp.mp.dps = 60

N = 128
MIN_NORMAL = 2.2250738585072014e-308


def as_bits(x: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def from_bits(u: int) -> float:
    return struct.unpack("<d", struct.pack("<Q", u))[0]


def emit(rows, xh, xl=0.0):
    if not (xh >= MIN_NORMAL and math.isfinite(xh)):
        return
    v = mp.log(mp.mpf(xh) + mp.mpf(xl))
    if v == 0:
        return  # log(1) = 0 exactly; no relative error to measure
    hi = float(v)
    lo = float(v - mp.mpf(hi))
    rows.append((xh, xl, hi, lo))


def main():
    rng = random.Random(20260725)
    rows = []

    # Both sides of 1, out to the adjacent doubles.
    one = as_bits(1.0)
    for i in range(1, 60):
        emit(rows, from_bits(one + i))
        emit(rows, from_bits(one - i))
    for e in range(1, 54):
        emit(rows, 1.0 + 2.0 ** -e)
        emit(rows, 1.0 - 2.0 ** -e)

    # Every slot, at both edges and the middle, in a few octaves.
    for j in range(N):
        for frac in (0.001, 0.5, 0.999):
            m = 1.0 + (j + frac) / N
            for k in (-900, -20, 0, 17, 900):
                emit(rows, math.ldexp(m, k))

    # The halving threshold.
    split = 1.0 + 53.0 / N
    for i in range(1, 20):
        emit(rows, from_bits(as_bits(split) + i))
        emit(rows, from_bits(as_bits(split) - i))

    # Exact powers of two: log must be k*ln2 alone.
    for k in range(-1022, 1024, 7):
        emit(rows, math.ldexp(1.0, k))

    # Uniform sweep across the exponent range.
    for _ in range(2500):
        emit(rows, math.ldexp(rng.uniform(1.0, 2.0), rng.randint(-1021, 1023)))

    # Ordinary magnitudes, where lgamma will actually call this.
    for _ in range(1500):
        emit(rows, rng.uniform(0.5, 400.0))

    # dd inputs: an exactly split product, the shape lgamma's recurrence
    # region produces before taking a log.
    for _ in range(800):
        a = rng.uniform(1.0, 30.0)
        b = rng.uniform(1.0, 30.0)
        prod = mp.mpf(a) * mp.mpf(b)
        hi = float(prod)
        emit(rows, hi, float(prod - mp.mpf(hi)))

    rows.sort(key=lambda t: t[0])
    print(f"# log reference: x_hi x_lo log_hi log_lo (hex doubles), {len(rows)} points")
    print("# generated by tools/gen_log_dd_reference.py; mpmath oracle at 60 dps")
    for xh, xl, hi, lo in rows:
        print(f"{xh.hex()} {xl.hex()} {hi.hex()} {lo.hex()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
