#!/usr/bin/env python3
"""Generate src/dd_special_data.h -- tables for the shared dd special
primitives in src/dd_special-inl.h (Log1pmxDd, Expm1Dd), consumed by the
incomplete gamma and incomplete beta kernels.

One piece:

  phi series    18 double coefficients (-1)^k/(k+2), k=0..17: the small-|u|
                branch of Log1pmxDd, phi(u) = u - log1p(u) = u^2*T(u). The
                k=0..5 leads also get a dd low word (kPhiCoefLo): plain-
                double rounding of 1/3 alone amplifies to ~12 ULP in the
                deep Temme tail (a*phi ~ 740) through e^{-a*phi} -- see
                self-check (b).

Self-checks (mandatory, budget lines to stderr; ANY miss -> exit nonzero,
emit nothing):
  (a) phi-series truncation at |u|=1/16 (the kPhiCut boundary).
  (b) phi-series leading dd pairs (k=0..5) reproduce their exact rational
      to <= 2^-107 relative.

Usage:
    python3 tools/gen_dd_special_data.py > src/dd_special_data.h
"""

import sys

import mpmath as mp

mp.mp.dps = 60

PHI_NTERMS = 18
PHI_CUT = mp.mpf(1) / 16
PHI_TARGET = mp.mpf(2) ** -74
PHI_LEAD = 6
PHI_LEAD_TARGET = mp.mpf(2) ** -107


def rd(x):
    return float(x)


def dd_split(x):
    hi = rd(x)
    return hi, rd(mp.mpf(x) - mp.mpf(hi))


def hexf(x):
    return float.hex(float(x))


def emit_hex_array_1d(name, vals):
    print(f"inline constexpr double {name}[{len(vals)}] = {{")
    print("    " + ", ".join(hexf(v) for v in vals) + ",")
    print("};")


def main():
    rc = 0
    phi_coefs = [((-1) ** k) / mp.mpf(k + 2) for k in range(PHI_NTERMS)]

    # --- self-check (a): phi series truncation --------------------------------
    print(f"(a) phi series {PHI_NTERMS}-term truncation at |u|=1/16:",
          file=sys.stderr)
    u = PHI_CUT
    T = mp.mpf(0)
    for c in reversed(phi_coefs):
        T = T * u + c
    phi_approx = u * u * T
    phi_exact = u - mp.log1p(u)
    rel_a = abs((phi_approx - phi_exact) / phi_exact)
    print(f"    rel err {float(rel_a):.3e} (2^{float(mp.log(rel_a, 2)):.2f}), "
          f"target 2^-74", file=sys.stderr)
    if rel_a > PHI_TARGET:
        print("    FAILED: exceeds 2^-74", file=sys.stderr)
        rc = 1

    # --- self-check (b): phi-series leading coefficients as dd pairs ----------
    # Rounding 1/3 alone is 2^-55.9 absolute, which enters phi at 2^-58.5
    # relative at the |u|=1/16 cut, and a*phi ~ 740 amplifies that to ~12 ULP
    # through the exponential -- the deep-Temme-tail band is exactly where a
    # small-u phi error gets blown up by e^{-a*phi}.
    print("(b) phi-series leading coefficients as dd pairs (k=0..5):",
          file=sys.stderr)
    phi_lead_dd = [dd_split(phi_coefs[k]) for k in range(PHI_LEAD)]
    worst_b = mp.mpf(0)
    worst_b_at = None
    for k in range(PHI_LEAD):
        exact = phi_coefs[k]
        hi, lo = phi_lead_dd[k]
        got = mp.mpf(hi) + mp.mpf(lo)
        rel = abs((got - exact) / exact)
        print(f"    k={k}: hi={hexf(hi)} lo={hexf(lo)} rel_err={float(rel):.3e}",
              file=sys.stderr)
        if rel > worst_b:
            worst_b, worst_b_at = rel, k
    worst_b_str = (f"2^{float(mp.log(worst_b, 2)):.2f}" if worst_b > 0 else "exact")
    print(f"    worst rel err {float(worst_b):.3e} ({worst_b_str}) at k={worst_b_at}, "
          f"target 2^-107", file=sys.stderr)
    if worst_b > PHI_LEAD_TARGET:
        print("    FAILED: exceeds 2^-107", file=sys.stderr)
        rc = 1

    if rc:
        print("One or more self-checks failed -- emitting nothing.", file=sys.stderr)
        return rc

    # --- emit ------------------------------------------------------------------
    print("// Auto-generated by tools/gen_dd_special_data.py. DO NOT EDIT.")
    print("// The error budget is documented in the generator; the kernel")
    print("// that consumes this is src/dd_special-inl.h.")
    print("#ifndef CORVUS_DD_SPECIAL_DATA_H_")
    print("#define CORVUS_DD_SPECIAL_DATA_H_")
    print()
    print("namespace corvus::detail {")
    print()
    print("// Log1pmxDd small-|u| branch: phi(u) = u - log1p(u) = u^2 * T(u),")
    print("// T(u) = sum_{k=0}^{17} (-1)^k/(k+2) * u^k, Horner in u.hi.")
    emit_hex_array_1d("kPhiCoef", [rd(c) for c in phi_coefs])
    print("// The k=0..5 leads carry a dd low word too: rounding 1/3 alone")
    print("// is 2^-55.9 absolute, which enters phi at 2^-58.5 relative at")
    print("// the |u|=1/16 cut, and a*phi ~ 740 amplifies that to ~12 ULP")
    print("// through e^{-a*phi} in the deep Temme tail.")
    print("// Exact-in-double entries (k=0: 1/2, k=2: 1/4) get lo=0.")
    emit_hex_array_1d("kPhiCoefLo", [p[1] for p in phi_lead_dd])
    print()
    print("// Series/log crossover for Log1pmxDd (see its derivation block).")
    print(f"inline constexpr double kPhiCut = {hexf(float(PHI_CUT))};")
    print()
    print("}  // namespace corvus::detail")
    print()
    print("#endif  // CORVUS_DD_SPECIAL_DATA_H_")
    return 0


if __name__ == "__main__":
    sys.exit(main())
