// Auto-generated by tools/gen_bessel_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/bessel-inl.h. See
// PLAN.md's P2 Bessel I0/I1 binding design and the G1 replay
// report for the split/klead/boundary derivations.
//
// All fits below are functions of q=x*x/4 or t=1/|x| -- both EVEN
// in x -- so a single table serves both signs: the kernel takes
// ax=|x| into every formula here and reapplies sign only at the very
// end for the odd i1/i1e (CopySign, not implicit propagation -- the
// dd assembly's internal Fast2Sum can turn -0 into +0 under IEEE
// round-to-nearest, the exact erfinv(-0) hazard src/erfinv-inl.h's
// ErfinvCentral already documents and guards the same way).
#ifndef CORVUS_BESSEL_DATA_H_
#define CORVUS_BESSEL_DATA_H_

namespace corvus::detail {

// Series/tail regime split, pinned by G1 replay (probe range [8,12]):
// x_s=8 is the ONLY candidate in range that reaches the 1 ULP series
// target without deep dd promotion -- x_s=10/12 were measured to
// plateau at 2-7 ULP regardless of dd-lead depth (larger x_s widens
// the series' own hump-shaped term profile near the domain edge,
// worsening Horner conditioning there faster than it shortens the
// tail fit). See the G1 report for the full split comparison.
inline constexpr double kBesselSplit = 0x1.0000000000000p+3;

// Overflow boundaries (unscaled i0/i1): last-finite double x,
// independently re-derived (bisected against the round-to-inf
// threshold 2^1024*(1-2^-54) at dps=50) and CONFIRMED bit-identical
// to the frontier probe's dps=40 derivation.
inline constexpr double kBesselI0OverflowX = 0x1.64fe5304e83e4p+9;
inline constexpr double kBesselI1OverflowX = 0x1.64fe69ff9fec7p+9;

// SERIES regime, x in [0, kBesselSplit]. i0e = S0(q)*exp_dd(-x);
// i1e = (x/2)*S1(q)*exp_dd(-x), q = x*x/4 captured EXACTLY (TwoProd/
// SquareLow-style residual -- q's own rounding costs ~x ULP here,
// NOT attenuated the way erfc's flat-in-u tail is) with a first-order
// derivative correction S(q_hi+q_lo)~=S(q_hi)+S'(q_hi)*q_lo using the
// *DCoef arrays below (plain double, cheap: the correction itself is
// already ~2^-53-relative). The lowest kBesselI{0,1}SeriesLead
// coefficients are dd (Hi/Lo); the remainder is one plain-double
// Horner pass (erfinv-inl.h ErfinvCentralDd's nested dd/double
// pattern) -- *SeriesCoef holds degrees [Lead..N] ascending.

inline constexpr int kBesselI0SeriesLead = 4;
inline constexpr int kBesselI0SeriesNCoef = 18;
inline constexpr double kBesselI0SeriesLeadHi[4] = {
    0x1.0000000000000p+0, 0x1.0000000000000p+0, 0x1.0000000000000p-2, 0x1.c71c71c71c71cp-6,
};
inline constexpr double kBesselI0SeriesLeadLo[4] = {
    0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.c71c71c71c71cp-60,
};
inline constexpr double kBesselI0SeriesCoef[18] = {
    0x1.c71c71c71c71cp-10, 0x1.23456789abcdfp-14, 0x1.02e85c0898b71p-19, 0x1.522a43f65486ap-25, 0x1.522a43f65486ap-31, 0x1.0b313289be0b9p-37,
    0x1.5601885e63e5dp-44, 0x1.69ca9cf3b7f54p-51, 0x1.4197a7f5154bcp-58, 0x1.e725594ee52e9p-66, 0x1.3e22d70ef3b5fp-73, 0x1.69f7da8510bcdp-81,
    0x1.69f7da8510bcdp-89, 0x1.40a2dc2460523p-97, 0x1.faaf2fa1c79e5p-106, 0x1.674f8e46c208cp-114, 0x1.cbeaf38dc529fp-123, 0x1.0afb53e9cec0bp-131,
};
inline constexpr double kBesselI0SeriesDCoef[21] = {
    0x1.0000000000000p+0, 0x1.0000000000000p-1, 0x1.5555555555555p-4, 0x1.c71c71c71c71cp-8, 0x1.6c16c16c16c17p-12, 0x1.845c8a0ce5129p-17,
    0x1.27e4fb7789f5cp-22, 0x1.522a43f65486ap-28, 0x1.2c9758daf5cd0p-34, 0x1.ab81ea75fcdf4p-41, 0x1.f17697cf1cf13p-48, 0x1.e2637bef9ff1ap-55,
    0x1.8bce58901a35ep-62, 0x1.165e7c2d153f3p-69, 0x1.53585cdcbfb10p-77, 0x1.69f7da8510bcdp-85, 0x1.54ad09e6a6575p-93, 0x1.1d028acb00491p-101,
    0x1.aaae78f4066a6p-110, 0x1.1f72d8389b3a3p-118, 0x1.5e69de22df5cep-127,
};

inline constexpr int kBesselI1SeriesLead = 4;
inline constexpr int kBesselI1SeriesNCoef = 18;
inline constexpr double kBesselI1SeriesLeadHi[4] = {
    0x1.0000000000000p+0, 0x1.0000000000000p-1, 0x1.5555555555555p-4, 0x1.c71c71c71c71cp-8,
};
inline constexpr double kBesselI1SeriesLeadLo[4] = {
    0x0.0p+0, 0x0.0p+0, 0x1.5555555555555p-58, 0x1.c71c71c71c71cp-62,
};
inline constexpr double kBesselI1SeriesCoef[18] = {
    0x1.6c16c16c16c17p-12, 0x1.845c8a0ce5129p-17, 0x1.27e4fb7789f5cp-22, 0x1.522a43f65486ap-28, 0x1.2c9758daf5cd0p-34, 0x1.ab81ea75fcdf4p-41,
    0x1.f17697cf1cf13p-48, 0x1.e2637bef9ff1ap-55, 0x1.8bce58901a35ep-62, 0x1.165e7c2d153f3p-69, 0x1.53585cdcbfb10p-77, 0x1.69f7da8510bcdp-85,
    0x1.54ad09e6a6575p-93, 0x1.1d028acb00491p-101, 0x1.aaae78f4066a6p-110, 0x1.1f72d8389b3a3p-118, 0x1.5e69de22df5cep-127, 0x1.84564b82a1184p-136,
};
inline constexpr double kBesselI1SeriesDCoef[21] = {
    0x1.0000000000000p-1, 0x1.5555555555555p-3, 0x1.5555555555555p-6, 0x1.6c16c16c16c17p-10, 0x1.e573ac901e574p-15, 0x1.bbd779334ef0bp-20,
    0x1.27e4fb7789f5cp-25, 0x1.2c9758daf5cd0p-31, 0x1.e0f227c4bc7b3p-38, 0x1.36ea1ee17216cp-44, 0x1.4ba46534bdf62p-51, 0x1.28dac26c13a86p-58,
    0x1.c45989c94286bp-66, 0x1.28ed514127baep-73, 0x1.53585cdcbfb10p-81, 0x1.54ad09e6a6575p-89, 0x1.2ed2b377b04dap-97, 0x1.e00448128737bp-106,
    0x1.555860c338552p-114, 0x1.b60455ab97342p-123, 0x1.fdb1431b736fdp-132,
};

// TAIL regime, x >= kBesselSplit. i_nu_e(x) = f_nu(t)/sqrt(2*pi*x),
// t = 1/x, f_nu Chebyshev-refit (own nodes/budget) in normalized
// s = t*Scale + Shift, s in [-1,1]. Plain-double Horner (erfc_tail
// precedent: t is flat/well-conditioned, no dd promotion needed --
// measured, klead 0/1/2 land at the same floor); the surrounding
// divide-by-sqrt is dd-assisted (DdSqrt then one rounding).

inline constexpr int kBesselI0TailNCoef = 27;
inline constexpr double kBesselI0TailScale = 0x1.0000000000000p+4;
inline constexpr double kBesselI0TailShift = -0x1.0000000000000p+0;
inline constexpr double kBesselI0TailCoef[27] = {
    0x1.02134d0ead7f4p+0, 0x1.1406bc8de01c2p-7, 0x1.66076ca936bdap-12, 0x1.d49ca2f947871p-16, 0x1.f337793296b15p-19, 0x1.902afc986bebbp-21,
    0x1.dd96d79ca1fd4p-23, 0x1.a75d8740cc21dp-24, 0x1.cfda3b4d63d51p-25, 0x1.45b90c3d1eee3p-26, -0x1.20ea23a20f2ccp-26, -0x1.21af45e671924p-25,
    -0x1.e003cbaa4f8f1p-27, 0x1.4b7d164928beep-26, 0x1.55333c8328814p-26, -0x1.491758b5ce046p-27, -0x1.2ad15a5094f89p-26, 0x1.55a452fce7f0ap-28,
    0x1.add13e94fa746p-27, -0x1.61b7edd0aad8cp-29, -0x1.eeb0e0e4e63bfp-28, 0x1.2e665de3e9900p-30, 0x1.9f8a834ffada1p-29, -0x1.5690988e8e7e7p-32,
    -0x1.ba5ef7117dc1bp-31, 0x1.6f0220f2a3638p-35, 0x1.b98c0a4f3a4fbp-34,
};

inline constexpr int kBesselI1TailNCoef = 27;
inline constexpr double kBesselI1TailScale = 0x1.0000000000000p+4;
inline constexpr double kBesselI1TailShift = -0x1.0000000000000p+0;
inline constexpr double kBesselI1TailCoef[27] = {
    0x1.f3c0639d4cae8p-1, -0x1.9066c647d50dcp-6, -0x1.201e5abc74426p-11, -0x1.3c37a5566edebp-15, -0x1.34a9bc518fb98p-18, -0x1.d4d5c5839e430p-21,
    -0x1.0d2ee805a3393p-22, -0x1.d04ff676184a6p-24, -0x1.f727a2b2598fcp-25, -0x1.6b4beca69e1afp-26, 0x1.2047605d098cbp-26, 0x1.2f16f9f4d8182p-25,
    0x1.08d59e5182181p-26, -0x1.4ef94a0c8b570p-26, -0x1.69c7ffedd36d2p-26, 0x1.409033d336913p-27, 0x1.38ff0d5026f9bp-26, -0x1.42be423205ba4p-28,
    -0x1.c00d5efbf5c63p-27, 0x1.49a4c5e5ccb29p-29, 0x1.01693b028be27p-27, -0x1.19999d0d94575p-30, -0x1.b049c443841a3p-29, 0x1.40341ffc09299p-32,
    0x1.cc3eb1b717e6cp-31, -0x1.588b2af155d19p-35, -0x1.cb80e4f12a381p-34,
};

}  // namespace corvus::detail

#endif  // CORVUS_BESSEL_DATA_H_
