// Auto-generated by tools/gen_betainv_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/betainv-inl.h. Consumes
// src/beta_data.h (region cores) and src/gammainv_data.h (S3's
// gamma-inverse seed machinery) alongside this header -- nothing
// already there is duplicated here.
#ifndef CORVUS_BETAINV_DATA_H_
#define CORVUS_BETAINV_DATA_H_

namespace corvus::detail {

// S1 beta-Temme seed: z=erfcinv(2*sigma) [sign by side], nu=alpha*beta/(alpha+beta),
// zeta0=sign*z/sqrt(nu) [note: NO factor of 2 -- beta's cpsi(lambda)=
// zeta^2*nu directly, unlike gamma's a*eta^2/2], invert cpsi(lambda)=
// zeta^2*nu for lambda via safeguarded Newton (exact analytic
// derivative lam*c/((a-lam)(b+lam)), c=a+b), y=(a-lambda)/c. Optional
// ONE perturbative-Newton correction: zeta_new = zeta0 -
// sign(zeta0)*S(zeta0,p)/(nu*sqrt(2)), S=sum c_k(zeta0,p)/nu^k,
// c_k a 2D Chebyshev fit over (zeta,p) [zeta in
// [-kBetaInvS1ZetaMax,kBetaInvS1ZetaMax], p in (0,0.5], symmetry
// c_k(zeta,p)=-c_k(-zeta,1-p)], gated to its own fitted domain AND
// nu>=kBetaInvS1NuMin (the 1/nu series is asymptotic; extrapolating
// below nu~2 was measured to diverge -- see final report).
inline constexpr int kBetaInvS1NCorr = 2;
inline constexpr int kBetaInvS1NZ = 15;
inline constexpr int kBetaInvS1NP = 9;
inline constexpr double kBetaInvS1ZetaMax = 0x1.c000000000000p+1;
inline constexpr double kBetaInvS1PMid = 0x1.0000000000000p-2;
inline constexpr double kBetaInvS1PHalf = 0x1.0000000000000p-2;
inline constexpr double kBetaInvS1NuMin = 0x1.0000000000000p+1;
inline constexpr double kBetaInvS1Cheb[2][15][9] = {
    {
        {-0x1.b771eb04da11ap-3, 0x1.b0ae5767634e0p-3, 0x1.0f2f16162c6c3p-8, -0x1.d95176a05e4d7p-11, 0x1.0d4e8525284eep-14, 0x1.fa61a033e7ae1p-18, -0x1.4666fcaa1046dp-18, 0x1.6bd01dca12729p-21, 0x1.41d22e694704fp-26},
        {-0x1.4ce6993511c50p-2, 0x1.82694db221880p-6, -0x1.0ce48b56b411ep-7, 0x1.5c5e0f2d8b66dp-10, -0x1.47bef45a14e35p-13, -0x1.3245e1295e9e1p-16, 0x1.1a32417e20502p-17, -0x1.72bcdf56f2fd5p-20, -0x1.569616d325922p-25},
        {-0x1.1b1c86d3612f2p-5, 0x1.05e1259c7f228p-5, 0x1.bc8ddb6dbdafep-9, -0x1.de884d0cb9d8dp-11, 0x1.ce2901e6a4d35p-14, 0x1.2bb6c1e112e85p-17, -0x1.f0f8b66049a4cp-18, 0x1.32be115eaf87cp-20, 0x1.3a278ae9d8279p-26},
        {0x1.04177c6c9f5adp-6, -0x1.58e130816f9b0p-7, 0x1.e3589f29f332dp-10, 0x1.fd62fa22dd0a4p-12, -0x1.45f2d46fdb415p-14, -0x1.2453a72b6a931p-18, 0x1.4844984ae3b22p-18, -0x1.068d18661e2bep-20, -0x1.0ad7dedff3510p-27},
        {0x1.6fa74e595a79ap-7, -0x1.4f5d1e777da88p-7, -0x1.151296a3d298ep-10, 0x1.03552cd2feaadp-16, 0x1.ec443623af414p-15, -0x1.e5b2a0f5270cdp-23, -0x1.958641a41b8c8p-19, 0x1.6ec63989d6a1dp-21, -0x1.066da52155a21p-26},
        {0x1.2739ce9852865p-9, 0x1.342f77ad829ddp-10, -0x1.471c97855d989p-13, -0x1.72ce97d1b5a4bp-15, -0x1.2762decb54ae8p-16, 0x1.0392d3ecec1eep-18, 0x1.84b23647b84e6p-20, -0x1.fc4d5330e623dp-22, 0x1.6cd20acef43f1p-26},
        {-0x1.29284b552fdafp-9, 0x1.3bf1814c474d5p-9, -0x1.5f43942b322f8p-13, 0x1.2d6f179691c79p-16, 0x1.255ae8242018ap-17, -0x1.47f4b7a26f109p-19, -0x1.71de24c6f4659p-22, 0x1.2e6047e788af3p-22, -0x1.e091793b8d9ebp-26},
        {-0x1.7cc398faa4a85p-10, 0x1.88eb57b2d801ep-11, -0x1.6dc891352f83dp-14, -0x1.93c660970518dp-15, -0x1.3affd2e79b974p-20, 0x1.2a1f0eca15615p-19, 0x1.be691fef95b04p-26, -0x1.279b37c833a38p-23, 0x1.a9e0137415f4dp-26},
        {0x1.2731d4f625e69p-14, -0x1.bb547b5d23beep-13, 0x1.3ddca0fabe8b9p-13, -0x1.31fc77156794dp-18, -0x1.64be756044494p-18, -0x1.f1c82a4d2a375p-21, 0x1.b1004225a2d4cp-23, 0x1.1eba71c1f92bep-24, -0x1.3befb31166c21p-26},
        {0x1.83b1291e386fdp-12, -0x1.b4c3bb26b9545p-12, 0x1.50c0d578f6910p-14, 0x1.56ce523ba8002p-17, 0x1.69044218af8c1p-21, -0x1.a36e418e522c1p-24, -0x1.2ffea7c84af98p-23, -0x1.6462b914c4b7ep-27, 0x1.ba31e9b563c0ep-27},
        {0x1.3067c0b0f11ecp-13, -0x1.15713f491583ap-13, -0x1.17259d4609d64p-16, 0x1.2644ab068c40ap-18, -0x1.4de924231b6f4p-21, -0x1.28be1eb4d8b74p-25, 0x1.043a6e4230469p-24, -0x1.81676aca80699p-29, -0x1.9903862e7128ep-28},
        {-0x1.011b67a559919p-15, 0x1.51596ca9713e2p-14, -0x1.05fafab29371fp-15, 0x1.3f0ff8ee7ef68p-18, 0x1.0020851cf9ffdp-21, -0x1.a435c5fe407c1p-23, -0x1.698d19bf65445p-25, 0x1.fc55c8530470ap-28, 0x1.7b912cbe12846p-29},
        {-0x1.e4b3d95c42976p-15, 0x1.3192a8965c335p-14, -0x1.059e66cf3a695p-16, -0x1.4548ecad92fffp-22, 0x1.8be7c658e500ep-21, 0x1.bf735aebd660cp-24, -0x1.5adee75d3864fp-27, -0x1.15fb8a9b3cf59p-27, -0x1.1778d9c54d022p-31},
        {-0x1.0d06942450184p-16, 0x1.230d510f720b8p-17, 0x1.1e16b66a49b59p-18, -0x1.a13aee1b28c0cp-19, 0x1.132db5d04960cp-25, 0x1.e09e079fbc16ep-25, 0x1.223f3eb8d72c8p-27, 0x1.c8d931f7091e1p-30, -0x1.0a498569aeda6p-31},
        {0x1.08c1fa378cc2fp-17, -0x1.04b411c2f1362p-16, 0x1.3c17c175cabb4p-17, -0x1.e64902a0201c8p-20, 0x1.fdb8848729409p-29, 0x1.6b9314c50da2ep-25, -0x1.276da0538edb2p-28, -0x1.15282d6f0777ep-29, 0x1.b1ef9ccb4a89cp-33},
    },
    {
        {0x1.392bc2c3c51a9p-7, -0x1.6aa826154c34bp-7, 0x1.dfd7edd4a1466p-10, -0x1.57c0cac782b26p-12, 0x1.e00fa70d8d3c7p-18, 0x1.45806d6790239p-20, -0x1.14a3b137cde7fp-20, 0x1.ffb2cc15ef254p-23, -0x1.c884e1a115f8dp-28},
        {0x1.dc609624b4453p-6, -0x1.30eef19cff11ap-7, 0x1.2ecdffb04c9abp-9, 0x1.8978d390a0c41p-16, -0x1.59b05941ee9c7p-17, -0x1.2c72849e66f52p-20, 0x1.f679c2ee1ca82p-20, -0x1.eceb7eee74399p-22, 0x1.ca79e8618242ep-27},
        {0x1.446ed454878eap-7, -0x1.359be1af77ca9p-7, -0x1.0cd4f4a9173fbp-11, 0x1.7e9708660701dp-15, 0x1.08f99814a1081p-16, -0x1.b3a620a4619ebp-24, -0x1.5c100f57a80fep-20, 0x1.a1e58fea0cad6p-22, -0x1.5dda1379fda27p-26},
        {0x1.318019eb182f1p-10, 0x1.5789834f42a46p-10, -0x1.e571173417965p-13, -0x1.3716b77e08fcbp-15, -0x1.02ce274b9546ap-17, 0x1.3e7bedef529d1p-19, 0x1.8196b68b2c50dp-21, -0x1.402e8943ce114p-22, 0x1.a1ee1ca06557cp-26},
        {-0x1.6fe841c2f7e5cp-9, 0x1.8397de0af2368p-9, -0x1.7d5ee033efdfdp-13, 0x1.e5386f14f2fbdp-16, 0x1.410a695e39412p-18, -0x1.1ba494cc2d7b1p-19, -0x1.cc3805b9ca73cp-24, 0x1.b8f8efe7e2701p-23, -0x1.de86f1320633bp-26},
        {-0x1.e38ca429f4307p-10, 0x1.dc32f7b0ea035p-11, -0x1.1c4922565dc8fp-13, -0x1.831e2905bbc57p-15, 0x1.0e85c8391d172p-21, 0x1.0334ee0fea6c0p-19, -0x1.99132c19274b8p-24, -0x1.d257511c5816ep-24, 0x1.cb3d9c8442ae9p-26},
        {0x1.423a11f78afbbp-13, -0x1.5b6302a22f4c3p-12, 0x1.98454b9223cc2p-13, -0x1.5f86348161075p-17, -0x1.91a109c550b14p-18, -0x1.ccaa836ad0dfbp-21, 0x1.0b2e2a186e101p-22, 0x1.d8502438a1c6dp-25, -0x1.66f88bd1c810cp-26},
        {0x1.3e0b058bc23bap-11, -0x1.531d9e9322566p-11, 0x1.1617cbf0c07a8p-13, 0x1.9ac1f7c801c75p-17, 0x1.17cddedb5b144p-20, -0x1.81b75f7243135p-23, -0x1.87b7b92bff06ap-23, -0x1.3d3ee5380b6c0p-28, 0x1.0985a87efd191p-26},
        {0x1.0511297f7ce39p-12, -0x1.e7282acea272dp-13, -0x1.68178c62cf9bep-16, 0x1.7bdd7dc7868ebp-18, -0x1.08283d2bf1013p-20, 0x1.747125a458b1cp-25, 0x1.5934bbe942a4ap-24, -0x1.4b47ccfba5102p-27, -0x1.072fd6f501049p-27},
        {-0x1.fb2e9951f008fp-15, 0x1.33e4304f1c10cp-13, -0x1.d03418c018661p-15, 0x1.18775534079f1p-17, 0x1.153bc70c445fep-21, -0x1.4a996add6f373p-22, -0x1.e0bfd7396f5f1p-25, 0x1.bbe0387f38620p-27, 0x1.dfca3f1c5addap-29},
        {-0x1.fd505ef387137p-14, 0x1.4067a8170d022p-13, -0x1.16409477d4fd7p-15, 0x1.3884d50a4057fp-22, 0x1.793f0f72b0e2ep-20, 0x1.50a51e8f5bd41p-23, -0x1.6d7c08d9fd72cp-26, -0x1.c23565cf8a9d2p-27, -0x1.946b9e307dafep-32},
        {-0x1.5ba1a940ee8bap-15, 0x1.f57564ce976d0p-16, 0x1.bd18980ba50cfp-19, -0x1.6918867380eb7p-18, 0x1.a11cddefc6e2ep-23, 0x1.0ae42c13291c4p-24, 0x1.ff5b3c590216bp-27, 0x1.cab56acc9d3d2p-29, -0x1.2372c6de2fe71p-30},
        {0x1.5a8647f129f1cp-16, -0x1.2970e6a785de2p-15, 0x1.26117eecc7bdfp-16, -0x1.5dbcb35b14a11p-19, -0x1.3696391565ecep-23, 0x1.108f338f7cb36p-25, -0x1.6830b11884b91p-28, -0x1.8d80038af9196p-30, 0x1.a0f3e2ff4b91bp-31},
        {0x1.9c8cab6a14723p-16, -0x1.0d957df8c4de8p-15, 0x1.07b9a408b5dd5p-17, 0x1.4d58c03ab11a9p-21, -0x1.adde5dd427c27p-22, 0x1.5999594ac01f1p-25, 0x1.17df4311c6885p-26, -0x1.09409b77922dbp-31, -0x1.ec909563a8273p-31},
        {0x1.3f21212fa85b5p-17, -0x1.4d9eb9382d800p-17, -0x1.51a52938272d8p-21, 0x1.8d82a2eab97bdp-20, -0x1.b336fdad9d1b1p-22, -0x1.87cc0751726b1p-26, 0x1.bc0d2d0992e8ep-28, 0x1.90dbb5bb61cabp-30, 0x1.f5f23ec20b556p-33},
    },
};

// S2 (small-y series inversion, either orientation via exact
// complement) Picard correction count.
inline constexpr int kBetaInvS2NCorr = 6;

// S4 (ORCHESTRATOR FIRST CORRECTION, 2026-08-09): exact-B leading-
// order closed form, exact in logit(y) of any sign/magnitude (not a
// linearization near the plateau center -- the original linear form
// (s-s*)/w+c(alpha,beta) diverged for |logit y|>>1; c(alpha,beta) is
// DROPPED here, not merely zero -- it actively hurt once B is exact):
//   s*=beta/(alpha+beta); s=sigma if side==p else 1-sigma
//   s<=s*: v=(ln s+ln alpha+lnB(alpha,beta))/alpha
//   s>s* : v=-(ln(1-s)+ln beta+lnB(alpha,beta))/beta
//   y=sigmoid(v)
// This is seed_S2's own zeroth iterate (either orientation, picked
// by which branch applies) -- S4 and S2 share one mechanism at
// leading order. Offered as a GLOBAL seed candidate at every (a,b,s)
// (selected by cheap-residual comparison like the other four);
// kBetaInvTJt is NOT a candidacy gate (the original design pinned it
// as one -- contract clarification, orchestrator ruling: t_jt gates
// only where the closed form could ship WITHOUT Newton refinement
// under the plateau backward-error contract, a G3/G4 kernel
// decision this generator does not make). Kept, PROVISIONAL, at its
// original measured value pending that decision.
inline constexpr double kBetaInvTJt = 0x1.0000000000000p-8;

// S5 (fix-hierarchy level (d), orchestrator-ratified last resort):
// logit-normal via EXACT digamma/trigamma moments of logit(Y) =
// ln(Gamma(alpha)-variate) - ln(Gamma(beta)-variate) [standard
// Gamma-ratio construction of Y~Beta(alpha,beta), clean-room]:
//   mu = psi(alpha)-psi(beta), var = psi'(alpha)+psi'(beta)
//   v = mu + Phi^-1(s)*sqrt(var), y = sigmoid(v)
// Targets "moderate shape, moderate probability" territory none of
// S1-S4 cover -- no pinned table (pure closed form on
// digamma/trigamma, evaluated by the kernel's own digamma/trigamma
// cores, corvus already ships both). Offered as a fifth global
// candidate, selected only when it wins the cheap-residual
// comparison.

// STEPS: safeguarded logit-Newton (m=lnP-lnQ, w=1/(y*dm/dy)),
// shared step count, gammainv G3 safeguard package (reject
// residual-increasing, 1/8 backtrack, bypass |resid|<TrustResid,
// multiplicative-in-y step y*(1+ls), floor ls>=-0.9).
// StepsN=4 [ORCHESTRATOR RULING, design amendment, 2026-08-09,
// gap-band escalation chain depth 2 -- see PLAN.md]: the original
// 3-step pin left a bounded interior sub-band (min(alpha,beta)
// approx 0.02-0.5, skew 3-10x, y interior 0.1-0.3) short of the
// gate after FIVE closed-form seed families were exhausted there
// (none exceeds ~2-5 bits; not a selection or noise-floor
// artifact, measured). Convergence from that band's worst
// measured seed is clean quadratic (2.12->6.66->16.48->36.16->
// 75.51 bits over steps 1-5); step 4 clears the gate by 20+ bits
// margin band-wide -- restores full margin, shaves nothing. The
// safeguard package makes step 4 IDEMPOTENT for lanes already
// converged after step 3 (freeze-by-select), so its cost is one
// bounded extra forward evaluation there, not a global slowdown.
// G3 LATITUDE: a whole-vector all-lanes-converged skip after step
// 3 is an ALLOWED bench optimization (gammainv's own "1 Halley
// vs 2 Newton" precedent) -- accuracy gates must hold either way;
// this is a throughput decision only, not an accuracy one.
inline constexpr int kBetaInvStepsN = 4;
inline constexpr double kBetaInvTrustResid = 0x1.0000000000000p-1;

// Deep-small closed-form cut, BOTH orientations [ORCHESTRATOR
// THIRD CORRECTION, 2026-08-09 -- re-derived, not the naive
// (own side)*y form, which has no dependence on the OTHER side's
// parameter and is wrong]. y0 = exp((ln sigma + ln alpha + lnB)/
// alpha) [P] or 1 - exp((ln sigma + ln beta + lnB)/beta) [Q] drops
// the series correction S' (S'->1 as y->0; S' = alpha*sum_n t_n/
// (alpha+n), t_0=1, t_n=t_{n-1}*(n-beta)*y/n). The dropped
// relative error in ln(y) is |ln S'|/alpha; its LEADING term is
// |1-beta|*y/(1+alpha) -- driven by the OTHER side's parameter
// (beta), not alpha (beta supplies the leading nonconstant series
// coefficient, n-beta at n=1; alpha enters only via the 1+alpha
// denominator) -- but the leading term ALONE under-predicts badly
// at the widened gamma-limit corner (measured true/bound ratio up
// to 13.8 uncorrected). CORRECTED with an EXACT closed-form
// multiplier corr(y')=-ln(1-y')/y' (y'=y [P] or 1-y [Q], the OWN
// side's small variable) -- exact in the huge-OTHER-side-exponent
// limit (S'->(1-y')^(other_side-1) there) and verified a SOUND
// (ratio<=1, worst measured 1.0000000004 -- boundary float noise)
// upper predictor across the full range tested; corr->1 as y'->0,
// so it reduces to the bare leading term exactly where that was
// already valid. Route:
//   P-side: |1-beta|*y/(1+alpha)*corr(y)         < kBetaInvDeepSmallCut
//   Q-side: |1-alpha|*(1-y)/(1+beta)*corr(1-y)   < kBetaInvDeepSmallCut
// Measured (self-check (f), bit-stepped at the boundary, full
// beta range including beta<1 and the widened gamma-limit corner
// beta up to 1e300): worst true dropped-factor error and worst
// true/bound ratio are both reported to stderr on every run --
// trust that budget line over this comment.
inline constexpr double kBetaInvDeepSmallCut = 0x1.0000000000000p-60;

}  // namespace corvus::detail

#endif  // CORVUS_BETAINV_DATA_H_
