// Auto-generated by tools/gen_dd_special_data.py. DO NOT EDIT.
// The error budget is documented in the generator; the kernel
// that consumes this is src/dd_special-inl.h.
#ifndef CORVUS_DD_SPECIAL_DATA_H_
#define CORVUS_DD_SPECIAL_DATA_H_

namespace corvus::detail {

// Log1pmxDd small-|u| branch: phi(u) = u - log1p(u) = u^2 * T(u),
// T(u) = sum_{k=0}^{17} (-1)^k/(k+2) * u^k, Horner in u.hi.
inline constexpr double kPhiCoef[18] = {
    0x1.0000000000000p-1, -0x1.5555555555555p-2, 0x1.0000000000000p-2, -0x1.999999999999ap-3, 0x1.5555555555555p-3, -0x1.2492492492492p-3, 0x1.0000000000000p-3, -0x1.c71c71c71c71cp-4, 0x1.999999999999ap-4, -0x1.745d1745d1746p-4, 0x1.5555555555555p-4, -0x1.3b13b13b13b14p-4, 0x1.2492492492492p-4, -0x1.1111111111111p-4, 0x1.0000000000000p-4, -0x1.e1e1e1e1e1e1ep-5, 0x1.c71c71c71c71cp-5, -0x1.af286bca1af28p-5,
};
// The k=0..5 leads carry a dd low word too: rounding 1/3 alone
// is 2^-55.9 absolute, which enters phi at 2^-58.5 relative at
// the |u|=1/16 cut, and a*phi ~ 740 amplifies that to ~12 ULP
// through e^{-a*phi} in the deep Temme tail.
// Exact-in-double entries (k=0: 1/2, k=2: 1/4) get lo=0.
inline constexpr double kPhiCoefLo[6] = {
    0x0.0p+0, -0x1.5555555555555p-56, 0x0.0p+0, 0x1.999999999999ap-57, 0x1.5555555555555p-57, -0x1.2492492492492p-57,
};

// Series/log crossover for Log1pmxDd (see its derivation block).
inline constexpr double kPhiCut = 0x1.0000000000000p-4;

}  // namespace corvus::detail

#endif  // CORVUS_DD_SPECIAL_DATA_H_
