// Auto-generated by tools/gen_digamma_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/digamma-inl.h.
#ifndef CORVUS_DIGAMMA_DATA_H_
#define CORVUS_DIGAMMA_DATA_H_

namespace corvus::detail {

// The unique positive root of digamma (~1.4616), as a dd pair.
// NOT to be confused with kDigammaX0 (the asymptotic threshold)
// below -- distinct constants that happen to share a name in
// the design prose (x0 the root vs X0 = 8 the threshold).
inline constexpr double kDigammaRootHi = 0x1.762d86356be3fp+0;
inline constexpr double kDigammaRootLo = 0x1.b86a722197829p-54;
// (x0.hi - 1), exact by Sterbenz (x0.hi in [1,2)): the (0,1)
// branch's shifted centre, reusing kDigammaRootLo unchanged.
inline constexpr double kDigammaRootM1Hi = 0x1.d8b618d5af8fcp-2;

// Region boundaries. [ZoneLo, ZoneHi) is the product-form zone;
// [ZoneHi, X0) walks down by up to kDigammaWalkDepth integer
// steps; [X0, inf) is the Bernoulli-series asymptotic form.
inline constexpr double kDigammaZoneLo = 0x1.0000000000000p+0;
inline constexpr double kDigammaZoneHi = 0x1.0000000000000p+1;
inline constexpr double kDigammaX0 = 0x1.0000000000000p+3;
inline constexpr int kDigammaWalkDepth = 6;

// Zone [1,2): psi(x) = t*P(t), t = x - root (dd). P(t) = 
// L0 + t*(L1 + ... + t*S(t)); L* are the first 2 dd-lead
// coefficients, S the plain-double tail (degree 21 total).
// Replay-measured worst relative error 2.441e-17 (target 2^-55).
inline constexpr int kDigammaZoneLead = 2;
inline constexpr int kDigammaZoneNCoef = 20;
inline constexpr double kDigammaZoneLeadHi[2] = {
    0x1.ef72bc8ee38acp-1, -0x1.c563b54aa1a2bp-2,
};
inline constexpr double kDigammaZoneLeadLo[2] = {
    -0x1.473a28c4f0cd6p-55, 0x1.a1ef87674306cp-57,
};
inline constexpr double kDigammaZoneCoef[20] = {
    0x1.08b4294d50395p-2, -0x1.4fc13172598b2p-3, 0x1.b9a5b6370de92p-4, -0x1.27baba24d962ep-4, 0x1.8fce02b1b1c38p-5, -0x1.0fa7eca55d68dp-5, 0x1.723d688a13c1bp-6, -0x1.f9702704949c0p-7, 0x1.5955a64b614e1p-7, -0x1.d82caeb34a3b2p-8, 0x1.42e6e557f720ap-8, -0x1.b95d44a9d2957p-9, 0x1.2db36a204a5ffp-9, -0x1.a0e4f33c67ca2p-10, 0x1.207213d1b8b4ap-10, -0x1.6d067620515adp-11, 0x1.bbdd7fb56106fp-12, -0x1.a7e9fae0307a4p-12, 0x1.a29076cfccbc4p-12, -0x1.6b107f71aa124p-13,
};

// Asymptotic (x >= kDigammaX0): psi(x) = log(x) - 1/(2x) - 
// x^-2*S(x^-2). S(w) = H0 + w*(H1 + ... + w*T(w)); H* are the
// first 1 dd-head coefficients (RAW Bernoulli
// series B_2k/(2k)), T the plain-double tail, K=9 terms
// total. Replay-measured worst relative error 9.821e-18 (target 2^-55).
inline constexpr int kDigammaAsymHead = 1;
inline constexpr int kDigammaAsymNCoef = 8;
inline constexpr double kDigammaAsymHeadHi[1] = {
    0x1.5555555555555p-4,
};
inline constexpr double kDigammaAsymHeadLo[1] = {
    0x1.5555555555555p-58,
};
inline constexpr double kDigammaAsymCoef[8] = {
    -0x1.1111111111111p-7, 0x1.0410410410410p-8, -0x1.1111111111111p-8, 0x1.f07c1f07c1f08p-8, -0x1.5995995995996p-6, 0x1.5555555555555p-4, -0x1.c5e5e5e5e5e5ep-2, 0x1.86e7f9b9fe6e8p+1,
};

// Reflection sinc-pair, v = u^2, u = x - round(x) (exact),
// |u| <= 1/2. sinc(u) = sin(pi u)/(pi u); cospi(u) = 
// cos(pi u); cot(pi x) = cospi(u) / (u * sinc(u)) (the (-1)^n
// parity from x = n + u cancels in the ratio). Both v-dd-lead
// + double-tail, matching the zone's DD evaluation shape.
// Replay: sinc worst 6.578e-19, cos worst 3.187e-18 (target 2^-58).
inline constexpr int kDigammaSincLead = 3;
inline constexpr int kDigammaSincNCoef = 6;
inline constexpr double kDigammaSincLeadHi[3] = {
    0x1.0000000000000p+0, -0x1.a51a6625307d3p+0, 0x1.9f9cb402bc3ebp-1,
};
inline constexpr double kDigammaSincLeadLo[3] = {
    -0x1.e8dfbd9fab477p-63, 0x1.de8704d0ca72ep-54, 0x1.8f4abb3e3653dp-55,
};
inline constexpr double kDigammaSincCoef[6] = {
    -0x1.86a8e472088a4p-3, 0x1.ac6805cbe14f0p-6, -0x1.3381697088111p-9, 0x1.37469730d3391p-13, -0x1.d3e3c296a65cfp-18, 0x1.07192db714f81p-22,
};
inline constexpr int kDigammaCosLead = 3;
inline constexpr int kDigammaCosNCoef = 7;
inline constexpr double kDigammaCosLeadHi[3] = {
    0x1.0000000000000p+0, -0x1.3bd3cc9be45dep+2, 0x1.03c1f081b5ac3p+2,
};
inline constexpr double kDigammaCosLeadLo[3] = {
    -0x1.e25e8cc1590fdp-68, -0x1.6347ff6504a25p-52, -0x1.e0a78ad223dc5p-55,
};
inline constexpr double kDigammaCosCoef[7] = {
    -0x1.55d3c7e3cbf5ep+0, 0x1.e1f5068913c52p-3, -0x1.a6d1f29e543bcp-6, 0x1.f9d3881e49dfdp-10, -0x1.b6e1921f719a3p-14, 0x1.209de0f1701fdp-18, -0x1.2084dd432a1bep-23,
};

// Rough trigamma (K=8 asymptotic Bernoulli terms, plain
// double, ~2^-40 relative): ONLY for the y.lo * trigamma(y.hi)
// correction on the reflection path's dd argument. NOT
// src/beta_data.h's DigammaRough (different function, different budget,
// not reusable -- see PLAN.md). Replay-measured worst 3.468e-13.
// WALK FORM (G3: mirror this in the kernel): while (y <
// kDigammaRoughTrigammaFloor) { s += 1/(y*y); y += 1; } then
// trigamma(y) ~= 1/y + w/2 + w*Horner(coef, w)/y, w = 1/(y*y),
// return s + that. y=2 alone measured ~2.4e-5 best-case (nowhere
// near 2^-40) -- the asymptotic series just isn't tight that
// close in; the walk floor is what buys the margin, not K.
inline constexpr double kDigammaRoughTrigammaFloor = 0x1.8000000000000p+2;
inline constexpr int kDigammaRoughTrigammaN = 8;
inline constexpr double kDigammaRoughTrigammaCoef[8] = {
    0x1.5555555555555p-3, -0x1.1111111111111p-5, 0x1.8618618618618p-6, -0x1.1111111111111p-5, 0x1.364d9364d9365p-4, -0x1.0330330330330p-2, 0x1.2aaaaaaaaaaabp+0, -0x1.c5e5e5e5e5e5ep+2,
};

}  // namespace corvus::detail

#endif  // CORVUS_DIGAMMA_DATA_H_
