// Auto-generated by tools/gen_erfc_tail_poly.py. DO NOT EDIT.
// Polynomial fits of G(u) = a*e^{a^2}*erfc(a), u = 1/a, in the
// normalized variable s = u*kErfcTailScale[i] + kErfcTailShift[i].
// Coefficients ascending; all intervals zero-padded to one degree
// so the kernel selects per-lane and runs a single Horner pass.
// Interval bounds (in a): [6,10], [10,17], [17,28].
#ifndef CORVUS_ERFC_TAIL_DATA_H_
#define CORVUS_ERFC_TAIL_DATA_H_

namespace corvus::detail {

inline constexpr int kErfcTailNCoef = 12;
inline constexpr double kErfcTailBound1 = 10.0;  // interval 0/1 split
inline constexpr double kErfcTailBound2 = 17.0;  // interval 1/2 split
inline constexpr double kErfcTailScale[3] = {
    0x1.e000000000002p+4,
    0x1.8492492492491p+5,
    0x1.5a2e8ba2e8ba3p+6,
};
inline constexpr double kErfcTailShift[3] = {
    -0x1.0000000000001p+2,
    -0x1.edb6db6db6db6p+1,
    -0x1.05d1745d1745dp+2,
};
inline constexpr double kErfcTailCoef[3][12] = {
    {  // a in [6.0, 10.0]
        0x1.1e5cec58b4786p-1,
        -0x1.38373feba12cfp-9,
        -0x1.1951959f6331ep-12,
        0x1.c6d38eaf43430p-18,
        0x1.125f03bc972f3p-22,
        -0x1.5a33b5e6ebdf5p-26,
        0x1.1b5be6b980f3ep-35,
        0x1.e8b32ed841a67p-35,
        -0x1.520ce1290f1e4p-39,
        -0x1.981f6d5557359p-44,
        0x1.f762b7504e6f8p-47,
        -0x1.985806e6f2b0ap-52,
    },
    {  // a in [10.0, 17.0]
        0x1.1ff675274b681p-1,
        -0x1.daaccad71fa01p-11,
        -0x1.da2387fb5b42cp-14,
        0x1.237e66f0d61d7p-20,
        0x1.00a372dfc3d8bp-24,
        -0x1.a313e7cf98bacp-30,
        -0x1.5f5d88dfcc7acp-35,
        0x1.54ee9ed36e882p-39,
        0x1.d8cefbdc2fa1fp-47,
        -0x1.21b1b03ca4ae1p-48,
        0x1.216a2804d2b61p-54,
        0x0.0p+0,
    },
    {  // a in [17.0, 28.0]
        0x1.208b1e3387470p-1,
        -0x1.40f76b75f9acfp-12,
        -0x1.35ab1815a9bd5p-15,
        0x1.01ccfdabc5ac2p-23,
        0x1.dc6b710bf5d0bp-28,
        -0x1.f99581bca7043p-35,
        -0x1.1a449aa4bf8b5p-39,
        0x1.2a032e89bd3dbp-45,
        0x1.9904e537fb9a6p-51,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
    },
};

}  // namespace corvus::detail

#endif  // CORVUS_ERFC_TAIL_DATA_H_
