// Auto-generated by tools/gen_erfinv_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/erfinv-inl.h.
#ifndef CORVUS_ERFINV_DATA_H_
#define CORVUS_ERFINV_DATA_H_

namespace corvus::detail {

// |y| <= kErfinvYSplit routes erfinv to the central core C.
inline constexpr double kErfinvYSplit = 0x1.0000000000000p-1;

// Central: Pc(v) = L0 + v*(L1 + v*(L2 + v*S(v))), v = y^2. L* dd,
// S the plain-double tail, single Horner pass.
inline constexpr int kErfinvCLead = 3;
inline constexpr int kErfinvCNCoef = 14;
inline constexpr double kErfinvCLeadHi[3] = {0x1.c5bf891b4ef6bp-1, 0x1.db29fb2fee5e4p-3, 0x1.053c2c0ab91e3p-3};
inline constexpr double kErfinvCLeadLo[3] = {-0x1.618cda9cca1ffp-55, -0x1.de36cfdd62401p-59, -0x1.51ea497be6f2fp-57};
inline constexpr double kErfinvCCoef[14] = {
    0x1.62847c47db76bp-4,
    0x1.0a13189d1b634p-4,
    0x1.a7c85c492a3c4p-5,
    0x1.5eeb253d1a88cp-5,
    0x1.2ab9eabd3625dp-5,
    0x1.03a351d5fa556p-5,
    0x1.c97a6c72314ecp-6,
    0x1.a219116020c1cp-6,
    0x1.3f270be2c6764p-6,
    0x1.1fc314d150e51p-5,
    -0x1.e4a80049cad23p-6,
    0x1.08c174cd08ae1p-3,
    -0x1.2d3f9f2cb597bp-3,
    0x1.1a55b7d7b8159p-3,
};

// T region boundaries (t = sqrt(-log s)). kErfinvTSplit divides
// the two mid seed intervals; kErfinvTFar is both the far/mid
// Halley split AND reuses erfc's own core/tail split (x = 6).
inline constexpr double kErfinvTSplit = 0x1.0000000000000p+1;
inline constexpr double kErfinvTFar = 0x1.8c7a44436a6f6p+2;

// Seed polynomials for x/t, index 0/1 in t on [t_lo,2]/[2,t_far],
// index 2 in u=1/t on [1/t_hi,1/t_far]. Padded to one degree so
// the kernel selects per-lane and runs a single Horner pass.
inline constexpr int kErfinvSeedNCoef = 10;
inline constexpr double kErfinvSeedCoef[3][10] = {
    {  // t in [t_lo, 2]
        -0x1.168a365953b14p-5,
        0x1.13a804b4aa5edp+0,
        -0x1.9663d51f7aa85p-2,
        -0x1.5ce4f56071ee6p-3,
        0x1.0a7ecfac8db3fp-2,
        -0x1.015a8eaa30be9p-3,
        0x1.e10443ec783f9p-6,
        -0x1.6d8419b9b579cp-9,
        0x0.0p+0,
        0x0.0p+0,
    },
    {  // t in [2, t_far]
        -0x1.5bdf0a077eeb2p-5,
        0x1.399ce5cdb64f7p+0,
        -0x1.9e26d17021d77p-1,
        0x1.670e5ea574f1ep-2,
        -0x1.ab911d5364dccp-4,
        0x1.60cf5e2e58679p-6,
        -0x1.8d1b5200d05b3p-9,
        0x1.231734fef23cap-12,
        -0x1.f539c39b6acaap-17,
        0x1.808d453f91a4cp-22,
    },
    {  // u = 1/t in [1/t_hi, 1/t_far]
        0x1.000ab17b62220p+0,
        -0x1.54e18c4df2d77p-6,
        -0x1.ae550784d9c48p+0,
        0x1.680ee0a9522fcp+2,
        -0x1.ee7ae9c8d9948p+3,
        0x1.57a359bcbff71p+4,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
    },
};

}  // namespace corvus::detail

#endif  // CORVUS_ERFINV_DATA_H_
