#ifndef CORVUS_EXP_DD_DATA_H_
#define CORVUS_EXP_DD_DATA_H_

#include <cstdint>

namespace corvus::detail {

// Tables for the double-double exp kernel (src/exp_dd-inl.h). Defined once in
// exp_dd_data.cpp so every SIMD target compiled by foreach_target shares a
// single copy. Generated by tools/gen_exp_table.py.
// Table size. Compile-time because the kernel shifts by it; the generated
// .inc static_asserts against the value it was built with.
inline constexpr int kExpLog2N = 7;
inline constexpr int64_t kExpN = int64_t{1} << kExpLog2N;

// Largest |x| the kernel accepts; it clamps to this, which is far outside the
// range where exp is finite and nonzero, so the clamp changes no result.
inline constexpr double kExpXMax = 1100.0;

extern const double kExpInvL;   // fl(kExpN / ln2)
extern const double kExpL1;     // ln2/kExpN, high part: k*kExpL1 is exact
extern const double kExpL2;     // ln2/kExpN - kExpL1, rounded
extern const double kExpTableHi[];  // 2^(j/N), high word
extern const double kExpTableLo[];  // 2^(j/N) - high word

}  // namespace corvus::detail

#endif  // CORVUS_EXP_DD_DATA_H_
