// Auto-generated by tools/gen_gamma_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/gamma-inl.h.
#ifndef CORVUS_GAMMA_DATA_H_
#define CORVUS_GAMMA_DATA_H_

namespace corvus::detail {

// Temme uniform-asymptotic coefficient table: row k holds the
// Chebyshev series (NOT monomial -- the kernel Clenshaw-evaluates
// each row directly) for c_k(eta), eta in [kGammaEtaMid -
// kGammaEtaHalf, kGammaEtaMid + kGammaEtaHalf] i.e. lambda in
// [1/2, 2]. S(eta, 1/a) = sum_{k=0}^{10} c_k(eta) / a^k, evaluated
// by Horner in r=1/a across the 11 rows.
inline constexpr int kGammaTemmeK = 11;
inline constexpr int kGammaTemmeNCoef = 21;
inline constexpr double kGammaEtaMid = 0x1.4b815d07de1b4p-4;
inline constexpr double kGammaEtaHalf = 0x1.67a8cdedec702p-1;
inline constexpr double kGammaTemmeCheb[11][21] = {
    {-0x1.522a9550e41b9p-2, 0x1.d46c87a40ebdcp-5, -0x1.d0c703eac0d82p-9, 0x1.a5dbcd8f36054p-14, 0x1.3e1b6b15af922p-17, -0x1.d23138ff66670p-20, 0x1.245395b0d1e84p-23, -0x1.b77aa7870e835p-29, -0x1.7dfd303a9c51ap-31, 0x1.f91984bcb8b8fp-34, -0x1.3acccf93a0a05p-37, 0x1.9a8c8a7ba761fp-43, 0x1.e1afca0c24338p-45, -0x1.3780c15fd20f6p-47, 0x1.859f38553b6e3p-51, -0x1.f0a5452473874p-57, -0x1.36f0b89f951e3p-58, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
    {-0x1.89e62825abb34p-10, -0x1.3993271ec732cp-9, 0x1.44bc300d04748p-11, -0x1.50d730549e349p-14, 0x1.8a043c556364ap-18, -0x1.bf51443748740p-26, -0x1.f557e5d2b6a64p-25, 0x1.2ed3e6e7e1b92p-27, -0x1.70deb23206a1cp-31, 0x1.7fdde2e36f0c5p-38, 0x1.b1866f7175b10p-38, -0x1.09bda0d75cdc5p-40, 0x1.4700c09934b6ap-44, -0x1.c5a9eb6ff7c98p-51, -0x1.6842a75d78b91p-51, 0x1.c0cc5aa7ee12cp-54, -0x1.17fbf0bc07cbdp-57, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
    {0x1.0ce09ca4f4868p-8, -0x1.d779ab9406ff5p-10, 0x1.75c44393c4a38p-13, -0x1.2ac43f51cf4e6p-25, -0x1.8847faf4d726cp-19, 0x1.0eaa34661ddd6p-21, -0x1.725e990349ebfp-25, 0x1.27943c64bb620p-32, 0x1.1c0be40010889p-31, -0x1.77afdd5e05c5dp-34, 0x1.f0074c13b9fedp-38, -0x1.2723d1be57585p-44, -0x1.4b09cd9fc9043p-44, 0x1.b17883a5058f8p-47, -0x1.1be5024f462e8p-50, 0x1.bd486873b843ep-57, 0x1.56e6ec15f833ep-57, -0x1.c3b15ebe945c2p-60, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
    {0x1.249da15042445p-11, 0x1.6edee8582d2d2p-13, -0x1.c96ea58bf379cp-14, 0x1.637e0fe3ee892p-16, -0x1.16663457638f0p-19, 0x1.6ebf6464969dbp-29, 0x1.2f7a41111b5ffp-25, -0x1.b5f15b6a9c99cp-28, 0x1.39bcb8b70fd75p-31, -0x1.0e84f182af309p-38, -0x1.06daa26d44288p-37, 0x1.6c4c62d0c385ap-40, -0x1.f821cee041ac8p-44, 0x1.4e1f61db494a5p-50, 0x1.6a3235fa89d99p-50, -0x1.f030af68191c0p-53, 0x1.5398dfb6428d4p-56, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
    {-0x1.c76239a054a9ap-11, 0x1.0f6d028b7ced4p-11, -0x1.16986cb913080p-14, -0x1.59b94b89281c5p-22, 0x1.e3651cdde0493p-20, -0x1.8d0ead5004004p-22, 0x1.3e0b6f9c296edp-25, -0x1.2beb271343083p-33, -0x1.5bb0093a3c6a0p-31, 0x1.0344b024fd67dp-33, -0x1.7fe521510e851p-37, 0x1.8dfa6cfabbf84p-44, 0x1.4ee3172fdab47p-43, -0x1.e1491b4bb5a0dp-46, 0x1.591df48bed886p-49, -0x1.02ed1809ebe6ep-55, -0x1.02ca5a88283f4p-55, 0x1.6fb1fec8b2e58p-58, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
    {-0x1.2362d7a602611p-12, -0x1.16f4421379a49p-14, 0x1.0f46b7bf90398p-14, -0x1.03c2dc8f9bdd6p-16, 0x1.e196da49d0094p-20, 0x1.cab420cae4e27p-29, -0x1.72831bdd6f8bcp-25, 0x1.2eab70b4175adp-27, -0x1.e6b7ee34f0696p-31, 0x1.33200bbc89bfap-38, 0x1.0a36c1a1647dfp-36, -0x1.951da5d1910dep-39, 0x1.32b5c9e636278p-42, -0x1.6ecb0238d3db3p-49, -0x1.11d8163bdf48dp-48, 0x1.9479b87f55a03p-51, -0x1.2a102b9eb108fp-54, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0},
    {0x1.1dd090bb29479p-11, -0x1.94aa6466fa380p-12, 0x1.e53207c7e50eep-15, 0x1.574b85be6821ep-21, -0x1.292e1ebc929a2p-19, 0x1.13698e98b11b2p-21, -0x1.ed71f7b8608a5p-25, 0x1.e6458da7f7dd5p-36, 0x1.61aedaa63b8eep-30, -0x1.20f346b5ed3a2p-32, 0x1.d30a56d8b2a9cp-36, -0x1.75ef1d606c5dcp-43, -0x1.fc10e42fa1303p-42, 0x1.88f903a56a10ap-44, -0x1.2ede3caf95fbbp-47, 0x1.9b060d9a3dddap-54, 0x1.11cc80d9e9d48p-53, -0x1.9d992657340c7p-56, 0x1.37a4a7d43a597p-59, 0x0.0p+0, 0x0.0p+0},
    {0x1.1bc5d02678624p-12, 0x1.168cc0cada15cp-14, -0x1.4a4c8d6a83349p-14, 0x1.68a389131a1cdp-16, -0x1.75ffd83dbce30p-19, -0x1.4a59de8c56fc6p-26, 0x1.79fd52d1f86e7p-24, -0x1.51f72ce688642p-26, 0x1.2806655cc1f3fp-29, -0x1.3184f51ef0731p-38, -0x1.9515521626b4bp-35, 0x1.4b4db0d1f0121p-37, -0x1.0d1a56ef6cc3cp-40, 0x1.02d67073a9879p-47, 0x1.2277e9dc2b95ep-46, -0x1.c7923660be8cep-49, 0x1.645a43b4ee48ap-52, -0x1.0de249f46be22p-58, -0x1.4418bc6ba34fep-58, 0x0.0p+0, 0x0.0p+0},
    {-0x1.6578a8f4f3870p-11, 0x1.1b58ad8f44d2cp-11, -0x1.78fc731196c42p-14, -0x1.e2b84afb0b234p-20, 0x1.30ba49364c45cp-18, -0x1.34457b0c29b13p-20, 0x1.2be27d1481a04p-23, 0x1.3822004b35bd6p-31, -0x1.0e08cea93dfeap-28, 0x1.d968ec2e9e866p-31, -0x1.998f8d96e8535p-34, 0x1.6c5246302d62bp-42, 0x1.0e31993c3add6p-39, -0x1.bb379df9c0ef6p-42, 0x1.69f8ac7ba04f9p-45, -0x1.960ff07cef591p-52, -0x1.83047993f5f46p-51, 0x1.3340ae25e0d79p-53, -0x1.e6e8e4c665655p-57, 0x0.0p+0, 0x0.0p+0},
    {-0x1.d20d2ed161fc6p-12, -0x1.094c8cb2bc0afp-13, 0x1.51bdeabd78a5dp-13, -0x1.943e64aeea3ccp-15, 0x1.c65314f8fcee5p-18, 0x1.93d3f771268cfp-24, -0x1.218283157501fp-22, 0x1.1552e52a7bb73p-24, -0x1.0369513637ec3p-27, -0x1.105e329da00c9p-36, 0x1.b007b9d9059cep-33, -0x1.762cb72da75f3p-35, 0x1.41748626bb1ecp-38, -0x1.8fb6b4a83b0b3p-46, -0x1.9b832d7cf0f42p-44, 0x1.52d28822ec778p-46, -0x1.1648803fa64e2p-49, 0x1.6410ac86434f7p-56, 0x1.266ade30c8333p-55, -0x1.d8c65ea1fb258p-58, 0x0.0p+0},
    {0x1.73435ef439e55p-10, -0x1.3f2b00b1da2e0p-10, 0x1.c94772d06980ap-13, 0x1.d05898e8b880cp-18, -0x1.d4ae1f2557300p-17, 0x1.fadc5e5a57161p-19, -0x1.067c92338b2cfp-21, -0x1.50d0d4cc31e52p-28, 0x1.20d674d8303acp-26, -0x1.0bb6269151031p-28, 0x1.e8defb023ce42p-32, 0x1.0a67119071a80p-43, -0x1.7fae09dd99e82p-37, 0x1.4a043d46ff1a1p-39, -0x1.1a8697a88723ap-42, 0x1.c097dc1e0cc50p-50, 0x1.6042871603e99p-48, -0x1.23622b090024cp-50, 0x1.e16f0d7601b19p-54, -0x1.5982e099f54d3p-60, -0x1.f79f33f98658ep-60},
};

// dd pairs of 1/n, n = 1..36 -- R4's alternating-series weights.
inline constexpr double kGammaRecipNHi[36] = {
    0x1.0000000000000p+0, 0x1.0000000000000p-1, 0x1.5555555555555p-2, 0x1.0000000000000p-2, 0x1.999999999999ap-3, 0x1.5555555555555p-3, 0x1.2492492492492p-3, 0x1.0000000000000p-3, 0x1.c71c71c71c71cp-4, 0x1.999999999999ap-4, 0x1.745d1745d1746p-4, 0x1.5555555555555p-4, 0x1.3b13b13b13b14p-4, 0x1.2492492492492p-4, 0x1.1111111111111p-4, 0x1.0000000000000p-4, 0x1.e1e1e1e1e1e1ep-5, 0x1.c71c71c71c71cp-5, 0x1.af286bca1af28p-5, 0x1.999999999999ap-5, 0x1.8618618618618p-5, 0x1.745d1745d1746p-5, 0x1.642c8590b2164p-5, 0x1.5555555555555p-5, 0x1.47ae147ae147bp-5, 0x1.3b13b13b13b14p-5, 0x1.2f684bda12f68p-5, 0x1.2492492492492p-5, 0x1.1a7b9611a7b96p-5, 0x1.1111111111111p-5, 0x1.0842108421084p-5, 0x1.0000000000000p-5, 0x1.f07c1f07c1f08p-6, 0x1.e1e1e1e1e1e1ep-6, 0x1.d41d41d41d41dp-6, 0x1.c71c71c71c71cp-6,
};
inline constexpr double kGammaRecipNLo[36] = {
    0x0.0p+0, 0x0.0p+0, 0x1.5555555555555p-56, 0x0.0p+0, -0x1.999999999999ap-57, 0x1.5555555555555p-57, 0x1.2492492492492p-57, 0x0.0p+0, 0x1.c71c71c71c71cp-58, -0x1.999999999999ap-58, -0x1.745d1745d1746p-59, 0x1.5555555555555p-58, -0x1.3b13b13b13b14p-58, 0x1.2492492492492p-58, 0x1.1111111111111p-60, 0x0.0p+0, 0x1.e1e1e1e1e1e1ep-61, 0x1.c71c71c71c71cp-59, 0x1.af286bca1af28p-59, -0x1.999999999999ap-59, 0x1.8618618618618p-59, -0x1.745d1745d1746p-60, 0x1.642c8590b2164p-60, 0x1.5555555555555p-59, -0x1.eb851eb851eb8p-61, -0x1.3b13b13b13b14p-59, 0x1.2f684bda12f68p-59, 0x1.2492492492492p-59, 0x1.1a7b9611a7b96p-61, 0x1.1111111111111p-61, 0x1.0842108421084p-60, 0x0.0p+0, -0x1.f07c1f07c1f08p-61, 0x1.e1e1e1e1e1e1ep-62, 0x1.0750750750750p-60, 0x1.c71c71c71c71cp-60,
};

// dd constants shared by the Temme prefactor and z.lo correction.
inline constexpr double kGammaTwoPiHi = 0x1.921fb54442d18p+2;
inline constexpr double kGammaTwoPiLo = 0x1.1a62633145c07p-52;
inline constexpr double kGammaInvSqrtPiHi = 0x1.20dd750429b6dp-1;
inline constexpr double kGammaInvSqrtPiLo = 0x1.1ae3a914fed80p-57;

// Region-map and fixed-length constants (all probe-validated).
inline constexpr double kGammaAT = 0x1.4000000000000p+4;
inline constexpr int kGammaSeriesN = 64;
inline constexpr int kGammaCfN = 44;
inline constexpr int kGammaR4N = 36;
inline constexpr double kGammaExpFloor = -0x1.9000000000000p+9;

}  // namespace corvus::detail

#endif  // CORVUS_GAMMA_DATA_H_
