// Auto-generated by tools/gen_gammainv_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/gammainv-inl.h. Consumes
// src/gamma_data.h (kGammaAT, region cores) alongside this header --
// nothing already there is duplicated here.
#ifndef CORVUS_GAMMAINV_DATA_H_
#define CORVUS_GAMMAINV_DATA_H_

namespace corvus::detail {

// S1 seed a_T: measured to coincide with the forward's own kGammaAT
// (self-check (e)/(f)); NOT redefined here -- the kernel reads
// detail::kGammaAT from gamma_data.h.

// lambda(eta) inversion of 1/2 eta^2 = lambda-1-ln(lambda): Taylor
// series (exact-rational coefficients, Horner in eta, double-
// rounded) for |eta| < kGammaInvEtaSeriesCut, else Newton in
// u=ln(lambda) with kGammaInvLamNewtonIters iterations from a
// sign-dependent asymptotic guess (self-check (a)/(b), floor
// 32.6 bits measured).
inline constexpr int kGammaInvLamSeriesOrder = 12;
inline constexpr double kGammaInvEtaSeriesCut = 0x1.0000000000000p-1;
inline constexpr int kGammaInvLamNewtonIters = 6;
inline constexpr double kGammaInvLamSeriesCoef[12] = {
    0x1.0000000000000p+0, 0x1.5555555555555p-2, 0x1.c71c71c71c71cp-6, -0x1.e573ac901e574p-9, 0x1.e573ac901e574p-13, 0x1.ed284dc73b445p-15, -0x1.ac6e36c515169p-16, 0x1.48c5892f7cd83p-18,
    -0x1.04bbf22109c3ap-22, -0x1.8e2825e109ef7p-23, 0x1.43f24731f751dp-24, -0x1.f9d4cd915b326p-27,
};

// S1 eta-correction table: eta_new = eta0 + (c0 + c1/a + ...)/a,
// c_k(eta) as a degree-kGammaInvCkNCoef-1 Chebyshev series over
// eta in [-kGammaInvEtaMax, kGammaInvEtaMax] (WIDE domain -- NOT
// gamma_data.h's kGammaTemmeCheb, which is fit only over the ridge
// band lambda in [1/2,2] and is the wrong table for this seed).
inline constexpr int kGammaInvCkRows = 2;
inline constexpr int kGammaInvSeedNCorr = 2;
inline constexpr int kGammaInvCkNCoef = 25;
inline constexpr double kGammaInvEtaMax = 0x1.27d1135318e42p+3;
inline constexpr double kGammaInvCkCheb[2][25] = {
    {-0x1.d1d89feb9f723p-2, 0x1.dcbea8162c0f2p-2, -0x1.c3038aa8b471cp-5, -0x1.478d5a25500adp-4, 0x1.0b9d45add5c5fp-5, 0x1.59145d259f3f8p-6, -0x1.2d74bbb1e805fp-6, -0x1.13bdba6efd653p-8, 0x1.3a77f1c172ec5p-7, -0x1.a9328763b5c21p-11, -0x1.249b761256616p-8, 0x1.d95664d80bfe4p-10, 0x1.c0118794bdd01p-10, -0x1.89c2e17859921p-10, -0x1.a205b95fb8ea1p-12, 0x1.eafba8222ccb6p-11, -0x1.c63302ae4fd43p-14, -0x1.ec6dd55f1d5e8p-12, 0x1.d27ba174b1db6p-13, 0x1.7a3479fde080fp-13, -0x1.7ff3ab2feede1p-13, -0x1.5ae36021908c8p-15, 0x1.ddcdd5bd78652p-14, -0x1.af87d72196ba5p-20, -0x1.24d988937670fp-14},
    {0x1.03f488b29b781p-5, -0x1.9761e603d99b3p-5, 0x1.e9c9ea9b3d68ap-7, 0x1.479b7a8a107e6p-7, -0x1.45266bd64c3e7p-7, -0x1.7e7e275883971p-10, 0x1.7a99f1bcbd098p-8, -0x1.463f30b89b046p-10, -0x1.73610f32757dap-9, 0x1.c8a8a8770b55cp-10, 0x1.0c0106119c3b6p-10, -0x1.6fe017adb36c3p-10, -0x1.6aa21889bd876p-14, 0x1.c74c46196ffacp-11, -0x1.20ab8caae8ac1p-12, -0x1.b2c7eedf512c8p-12, 0x1.520db7a82fb88p-12, 0x1.02678a89f5145p-13, -0x1.f2b741abdebb7p-13, 0x1.474225adc1ebdp-16, 0x1.0d108a0c873edp-13, -0x1.f2a5bda9ba96ep-15, -0x1.6c93878e12520p-15, 0x1.5ec8dd67d8a20p-15, -0x1.8564826a10814p-22},
};

// S2 (p-side, a<a_T small-side seed) Picard correction count.
inline constexpr int kGammaInvS2NCorr = 6;
// S3 (q-side far-tail fixed-point seed) iteration count. a<a_T,
// side='q': try S3 first, gated by its OWN
// L=-ln(q*Gamma(a)) > kGammaInvS3StabilityMargin*|a-1| guard (the
// fixed-point map's local contraction factor is (a-1)/x -- L>0
// ALONE is insufficient, and neither is a fixed q threshold: both
// were tried and found wrong, see final report ledger); S2 applied
// to p=1-q is the fallback whenever S3 declines.
inline constexpr double kGammaInvS3StabilityMargin = 0x1.8000000000000p+1;
inline constexpr int kGammaInvS3NIter = 3;

// a<a_T seed selection (side='p' and side='q' alike): compute the
// S1 candidate (when a>=kGammaInvS1AMin and |eta0|<=kGammaInvEtaMax)
// AND the S2-or-S3 candidate, then pick by a CHEAP low-precision
// forward-residual comparison (one extra forward eval, selector
// only -- not precision-bearing). Neither candidate alone covers
// the whole a<a_T domain (self-check (f)): S1 needs a not too
// small; S2/S3 degrade as a->a_T outside their own genuine-tail/
// near-median comfort zones. Not in the original design sketch,
// which conditioned S1 on a>=a_T alone; forced by replay.
inline constexpr double kGammaInvS1AMin = 0x1.3333333333333p-2;

// dd-Newton step count (shared) + per-depth-bucket variant, pinned
// by replay (self-check (f)) under the consistent root(s)
// comparison basis: log-residual Newton wins BOTH depth buckets
// (plain Newton leaves shallow worst cases in the 20-30 bit
// range). Both booleans are emitted separately so a future
// re-measure can split the variants per bucket without a
// header-format change.
// bucket=deep: variant=ln nsteps=3 measured_floor=59.68b
// bucket=shallow: variant=ln nsteps=3 measured_floor=57.54b
inline constexpr int kGammaInvStepsN = 3;
inline constexpr double kGammaInvShallowThreshold = 0x1.0000000000000p-10;
inline constexpr bool kGammaInvStepsLogResidualDeep = true;
inline constexpr bool kGammaInvStepsLogResidualShallow = true;

// Deep-small closed-form cut: a*x0 < kGammaInvDeepSmallCut routes to
// the exp_dd((LogDd(p) (+) dd lnGamma(1+a)) / a) closed form.
inline constexpr double kGammaInvDeepSmallCut = 0x1.0000000000000p-60;

}  // namespace corvus::detail

#endif  // CORVUS_GAMMAINV_DATA_H_
