// Auto-generated by tools/gen_lgamma_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/lgamma-inl.h.
#ifndef CORVUS_LGAMMA_DATA_H_
#define CORVUS_LGAMMA_DATA_H_

namespace corvus::detail {

// Region boundaries. (0, LO) shifts by one log; [LO, MID) and
// [MID, HI] are the zero-centred polynomials; (HI, X0) walks down
// to [MID, HI] by the product recurrence; [X0, inf) is Stirling.
inline constexpr double kLgammaZoneLo = 0x1.0000000000000p-1;
inline constexpr double kLgammaZoneMid = 0x1.8000000000000p+0;
inline constexpr double kLgammaZoneHi = 0x1.4000000000000p+1;
inline constexpr double kLgammaX0 = 0x1.0000000000000p+3;
inline constexpr int kLgammaMidSteps = 6;

// Largest argument with a finite result; above it lgamma overflows.
inline constexpr double kLgammaMaxArg = 0x1.754d9278b51a7p+1014;

// B(t) = L0 + t*(L1 + t*(L2 + t*S(t))), t = x - centre, index 0 is
// centre 1 and index 1 is centre 2. L* are double-double; S is the
// plain-double tail, zero-padded to one degree for a single Horner.
inline constexpr int kLgammaZoneLead = 3;
inline constexpr int kLgammaZoneNCoef = 32;
inline constexpr double kLgammaZoneLeadHi[2][3] = {
    {-0x1.2788cfc6fb619p-1, 0x1.a51a6625307d3p-1, -0x1.9a4d55beab2d7p-2},
    {0x1.b0ee6072093cep-2, 0x1.4a34cc4a60fa6p-2, -0x1.13e001a557606p-4},
};
inline constexpr double kLgammaZoneLeadLo[2][3] = {
    {0x1.6cbb7e0fe86efp-58, 0x1.1918bdcb1ec53p-56, 0x1.1a98aa03d7ad5p-59},
    {0x1.6ca968e874666p-58, 0x1.1889ad659918cp-56, -0x1.c9b36750dfa4cp-58},
};
inline constexpr double kLgammaZoneCoef[2][32] = {
    {  // centre 1
        0x1.151322ac7d848p-2,
        -0x1.a8b9c17aa6144p-3,
        0x1.5b40cb100c3fcp-3,
        -0x1.2703a1dcea718p-3,
        0x1.010b36af7f710p-3,
        -0x1.c806706d31d47p-4,
        0x1.9a01e3894260ap-4,
        -0x1.748c331956c98p-4,
        0x1.556ad5a5aaa3ep-4,
        -0x1.3b1d96002c2e6p-4,
        0x1.2496eed48a19cp-4,
        -0x1.1113507ad95e5p-4,
        0x1.ffffa326480ebp-5,
        -0x1.e1dee1e2fed8fp-5,
        0x1.c73ef9335c3c8p-5,
        -0x1.af5d1c63d5ab4p-5,
        0x1.982dac1ebc9f3p-5,
        -0x1.840ce0cc66b47p-5,
        0x1.7fb6f89f0edf4p-5,
        -0x1.738de7e162290p-5,
        0x1.11a03b7bcdd51p-5,
        -0x1.e14e12e0fbd94p-6,
        0x1.32f91b7620c73p-4,
        -0x1.4eebfcdf93365p-4,
        -0x1.4af6ce9f30614p-4,
        0x1.a36b8d4bf294dp-4,
        0x1.2a14095271792p-2,
        -0x1.4b2b8d2f1ead7p-2,
        -0x1.52e426c6ecfcbp-2,
        0x1.74b60c5a34935p-2,
        0x1.29f57ba7f4881p-2,
        -0x1.363210978c208p-2,
    },
    {  // centre 2
        0x1.51322ac7d8483p-6,
        -0x1.e404fc218f684p-8,
        0x1.7add6eadb6db4p-9,
        -0x1.38ac5c2beff8bp-10,
        0x1.0b36af8627551p-11,
        -0x1.d3fd4c7faf4dbp-13,
        0x1.a127b1007e5c4p-14,
        -0x1.78de594676137p-15,
        0x1.580dcb1b4ee28p-16,
        -0x1.3cbd0cba0efb7p-17,
        0x1.259840f278775p-18,
        -0x1.11a54008a9871p-19,
        0x1.005428458d1c7p-20,
        -0x1.e463a6e6a92e8p-22,
        0x1.c9b41c1a66e17p-23,
        -0x1.980bc6e3ae864p-24,
        0x1.80dfde14eb9d5p-25,
        -0x1.0d0be536a48afp-25,
        0x1.04ee316d03b68p-26,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
        0x0.0p+0,
    },
};

// phi(x) = psi(w)/x with w = 1/x^2: the Stirling remainder. Plain
// double is enough -- phi is ~1/(12x), so even a full ULP of it is
// ~2^-60 of lgamma(X0), the tightest point in the region.
inline constexpr int kLgammaStirNCoef = 9;
inline constexpr double kLgammaStirCoef[9] = {
    0x1.5555555555555p-4,
    -0x1.6c16c16c16c0fp-9,
    0x1.a01a01a00d48fp-11,
    -0x1.381381170573ap-11,
    0x1.b951b77bfdba8p-11,
    -0x1.f69b140c51536p-10,
    0x1.a258ac6867bf7p-8,
    -0x1.c6a01542fb5aep-6,
    0x1.c2f9d3c217f40p-4,
};
inline constexpr double kLgammaHalfLog2PiHi = 0x1.d67f1c864beb5p-1;
inline constexpr double kLgammaHalfLog2PiLo = -0x1.65b5a1b7ff5dfp-55;

// log(sin(pi u)/(pi u)) = v*(M0 + v*(M1 + v*T(v))), v = u^2.
inline constexpr int kLgammaSinLead = 2;
inline constexpr int kLgammaSinNCoef = 16;
inline constexpr double kLgammaSinLeadHi[2] = {-0x1.a51a6625307d3p+0, -0x1.151322ac7d848p-1};
inline constexpr double kLgammaSinLeadLo[2] = {-0x1.18733e75f65a2p-55, -0x1.c2130eaef9fe3p-56};
inline constexpr double kLgammaSinCoef[16] = {
    -0x1.5b40cb100c301p-2,
    -0x1.010b36af866edp-2,
    -0x1.9a01e385b0d42p-3,
    -0x1.556ad63a1e45ap-3,
    -0x1.2496de6a36fbcp-3,
    -0x1.00011bc1e6620p-3,
    -0x1.c71909f2351d7p-4,
    -0x1.99ccf4cd0a952p-4,
    -0x1.725dc72209b61p-4,
    -0x1.645aba155a161p-4,
    -0x1.cc2bfff5aafefp-5,
    -0x1.45350c040ffe4p-3,
    0x1.9af163adc6ffdp-3,
    -0x1.43192ddabf262p-1,
    0x1.6c07d8f9b79acp-1,
    -0x1.2e9fb1a8fe3bdp-1,
};

}  // namespace corvus::detail

#endif  // CORVUS_LGAMMA_DATA_H_
