#ifndef CORVUS_LOG_DD_DATA_H_
#define CORVUS_LOG_DD_DATA_H_

#include <cstdint>

namespace corvus::detail {

// Tables for the double-double log kernel (src/log_dd-inl.h). Defined once in
// log_dd_data.cpp so every SIMD target compiled by foreach_target shares a
// single copy. Generated by tools/gen_log_table.py.

// Slot count and the index shift that extracts it from the mantissa.
// Compile-time because the kernel shifts by them; the generated .inc
// static_asserts against the values it was built with.
inline constexpr int kLogLog2N = 7;
inline constexpr int64_t kLogN = int64_t{1} << kLogLog2N;
inline constexpr int kLogShift = 52 - kLogLog2N;  // mantissa bits below j
// j >= this halves the mantissa, centring it on 1.
inline constexpr int64_t kLogSplitSlot = 53;

extern const double kLogSplit;    // 1 + kLogSplitSlot/kLogN
extern const double kLogLn2Hi;
extern const double kLogLn2Lo;
extern const double kLogTableR[];    // R_j
extern const double kLogTableLHi[];  // -log(R_j), high word
extern const double kLogTableLLo[];  // -log(R_j), low word

}  // namespace corvus::detail

#endif  // CORVUS_LOG_DD_DATA_H_
