#ifndef CORVUS_TRIG_PH_DATA_H_
#define CORVUS_TRIG_PH_DATA_H_

namespace corvus::detail {

// Payne-Hanek windows for the cos/sin kernels' large-argument region
// (|x| > kTrigDMax = 2^23; small-region constants live in trig_data.h).
// Defined once in trig_ph_data.cpp so every SIMD target compiled by
// foreach_target shares a single copy. Generated by
// tools/gen_trig_ph_table.py, which certifies the windows end-to-end at
// each exponent's continued-fraction worst cases, including binary64's
// deepest reduction cancellation (|r| = 2^-60.89 at e = 849).

// Row index = unbiased exponent of |x| minus kTrigPhEMin. Compile-time
// because the kernel computes the index from the exponent field; the
// generated .inc static_asserts against the values it was built with.
inline constexpr int kTrigPhEMin = 23;
inline constexpr int kTrigPhRows = 1001;  // e = 23..1023 inclusive

// pi/2 as a dd pair (relative error 2^-109.7): r = (f - n) * pi/2.
extern const double kTrigPio2DdHi;
extern const double kTrigPio2DdLo;

// W_e = (2^(e-52) * 2/pi) mod 4, four 53-bit chunks at fixed weights
// (2^1..2^-51 / ..2^-104 / ..2^-157 / ..2^-210). Every chunk is a 53-bit
// integer times a power of two, so every mantissa*chunk product is an
// exact dd via TwoProd; window truncation costs < 2^-157 absolute in f.
extern const double kTrigPhTab0[];
extern const double kTrigPhTab1[];
extern const double kTrigPhTab2[];
extern const double kTrigPhTab3[];

}  // namespace corvus::detail

#endif  // CORVUS_TRIG_PH_DATA_H_
