// Auto-generated by tools/gen_trig_table.py. DO NOT EDIT.
// Small-argument-region constants for the cos/sin kernels
// (src/trig-inl.h). Clean-room provenance and the derivation live in
// the generator's docstring; the values are bit-identical to the
// certified donor constants (generator self-check).
#ifndef CORVUS_TRIG_DATA_H_
#define CORVUS_TRIG_DATA_H_

namespace corvus::detail {

// Small-region domain bound: n*part_k products are exact only for
// |n| < 2^23. NOT a public domain limit -- beyond it the kernel
// routes to the Payne-Hanek region (trig_ph_data.h).
inline constexpr double kTrigDMax = 0x1.0000000000000p+23;  // 2^23
inline constexpr double kTrigTwoOverPi = 0x1.45f306dc9c883p-1;

// pi/2 split: parts 0-2 carry 30 significant bits each, so n*part_k
// is exact for |n| < 2^23 WITHOUT FMA; part 3 is a full 53-bit tail
// whose product rounds (<= 2^-124 absolute, below the reduction's
// ~2^-60 error floor). Subtract in order, compensated.
inline constexpr double kTrigPio2[4] = {
    0x1.921fb54800000p+0,
    -0x1.de973dc800000p-31,
    -0x1.9d9cceb800000p-62,
    -0x1.1fc8f8cbb5bf7p-93,
};

// Degree-6 near-minimax parity cores on u = r^2 in [0, (pi/4)^2
// (padded)]: sin(r) = r + r*(u*P(u)); cos(r) = 1 + u*Q(u).
// kTrigCosC[0] == -1/2 EXACTLY (generator-asserted): the kernel's
// exact 1 - u/2 head/tail split depends on it.
inline constexpr double kTrigSinC[7] = {
    -0x1.5555555555555p-3,
    0x1.1111111111110p-7,
    -0x1.a01a01a019938p-13,
    0x1.71de3a5460952p-19,
    -0x1.ae645412c46d3p-26,
    0x1.61217f0abf087p-33,
    -0x1.ab17d393166dcp-41,
};
inline constexpr double kTrigCosC[7] = {
    -0x1.0000000000000p-1,
    0x1.5555555555551p-5,
    -0x1.6c16c16c15d79p-10,
    0x1.a01a019de130cp-16,
    -0x1.27e4f8e4a1e4cp-22,
    0x1.1eea7f24ce4e2p-29,
    -0x1.8ff9d3c0d9835p-37,
};

}  // namespace corvus::detail

#endif  // CORVUS_TRIG_DATA_H_
