// Auto-generated by tools/gen_trigamma_data.py. DO NOT EDIT.
// Fits and their error budgets are documented in the generator;
// the kernel that consumes them is src/trigamma-inl.h.
#ifndef CORVUS_TRIGAMMA_DATA_H_
#define CORVUS_TRIGAMMA_DATA_H_

namespace corvus::detail {

// Region boundaries. [ZoneLo, ZoneHi) is the plain value-fit
// zone (NO product form -- trigamma has no zero to divide out,
// unlike digamma); [ZoneHi, X0) walks down by up to
// kTrigammaWalkDepth integer steps; [X0, AsymCut) is the direct
// Bernoulli-sum asymptotic form; [AsymCut, inf) is fl(1/x) alone.
inline constexpr double kTrigammaZoneLo = 0x1.0000000000000p+0;
inline constexpr double kTrigammaZoneHi = 0x1.0000000000000p+1;
// The zone fit's own centre (exact double, 1.5 -- NOT a root;
// trigamma has none). kTrigammaZoneCentreM1 = centre - 1,
// exact, is the (0,1) branch's shift: t1 = x - CentreM1 =
// (x+1) - centre, evaluating zone(x+1) WITHOUT forming 1+x.
inline constexpr double kTrigammaZoneCentre = 0x1.8000000000000p+0;
inline constexpr double kTrigammaZoneCentreM1 = 0x1.0000000000000p-1;
inline constexpr double kTrigammaX0 = 0x1.0000000000000p+3;
inline constexpr int kTrigammaWalkDepth = 6;
inline constexpr double kTrigammaAsymCut = 0x1.0000000000000p+89;

// Zone [1,2): psi_1(x) = P(t), t = x - kTrigammaZoneCentre (dd).
// P(t) = L0 + t*(L1 + ... + t*S(t)); L* are the first 3 dd-lead
// coefficients [FIRST CORRECTION: 3, not the probe's 1 -- see
// PLAN.md; the original '1 dd-lead' number was a grid artifact,
// missed by uniform/random sampling, that edge-refined bit-
// stepped replay near x=1/x=2 caught], S the plain-double tail
// (degree 27 total). Replay-measured worst relative
// error 9.598e-18 (target 2^-55).
inline constexpr int kTrigammaZoneLead = 3;
inline constexpr int kTrigammaZoneNCoef = 25;
inline constexpr double kTrigammaZoneLeadHi[3] = {
    0x1.de9e64df22ef3p-1, -0x1.a85808a40aba2p-1, 0x1.68ba30a420963p-1,
};
inline constexpr double kTrigammaZoneLeadLo[3] = {
    -0x1.6d7834829923bp-56, -0x1.3013a6ebad877p-56, 0x1.8d8936c882f45p-55,
};
inline constexpr double kTrigammaZoneCoef[25] = {
    -0x1.287825428e74ap-1, 0x1.da2d963cfe929p-2, -0x1.72d7487c33924p-2, 0x1.1cc1377b9ba3ap-2, -0x1.aeb6f1555330bp-3, 0x1.41a51bebab685p-3, -0x1.db4d85481a3c3p-4, 0x1.5c083d1688f49p-4, -0x1.f9c6ebbd6939ep-5, 0x1.6d16d0265e3f1p-5, -0x1.060835f08e4c7p-5, 0x1.764390179e0e3p-6, -0x1.0a1ce8fb9b964p-6, 0x1.78e692cb3d97ap-7, -0x1.0a09ad818ff39p-7, 0x1.7756e1157df00p-8, -0x1.076177f0f0f35p-8, 0x1.67c57f070e409p-9, -0x1.f6b238ea2033dp-10, 0x1.99ef91b6a4736p-10, -0x1.1cce282a159b3p-10, 0x1.110d660d56e47p-12, -0x1.7e8d1fecf43d0p-13, 0x1.8dce1f22fa30cp-11, -0x1.1271c6220b5b9p-11,
};

// Asymptotic (x >= kTrigammaX0): psi_1(x) = 1/x + 1/(2x^2) + 
// x^-3*S(x^-2). S(w) = H0 + w*(H1 + ... + w*T(w)); H* are the
// first 1 dd-head coefficients (DIRECT, unfactored
// Bernoulli series B_2k -- NOT divided by 2k, unlike digamma's
// asymptotic coefficients: trigamma is digamma's derivative,
// which removes the /(2k) and adds one power of 1/x per term).
// T the plain-double tail, K=11 terms total. Replay-measured worst relative error 1.418e-17 (target 2^-55). Beyond kTrigammaAsymCut, the dropped part (1/(2x^2) + tail) is < 2^-90 relative of 1/x (measured 8.078e-28), so fl(1/x) alone suffices there.
inline constexpr int kTrigammaAsymHead = 1;
inline constexpr int kTrigammaAsymNCoef = 10;
inline constexpr double kTrigammaAsymHeadHi[1] = {
    0x1.5555555555555p-3,
};
inline constexpr double kTrigammaAsymHeadLo[1] = {
    0x1.5555555555555p-57,
};
inline constexpr double kTrigammaAsymCoef[10] = {
    -0x1.1111111111111p-5, 0x1.8618618618618p-6, -0x1.1111111111111p-5, 0x1.364d9364d9365p-4, -0x1.0330330330330p-2, 0x1.2aaaaaaaaaaabp+0, -0x1.c5e5e5e5e5e5ep+2, 0x1.b7c4f8f13e3c5p+5, -0x1.088fe72cfe72dp+9, 0x1.8301f89467e25p+12,
};

// Reflection sinc fit, v = u^2, u = x - round(x) (exact),
// |u| <= 1/2. sinc(u) = sin(pi u)/(pi u). pi^2/sin^2(pi x) =
// 1/(u*sincfit(u))^2 -- NO cos table needed (unlike digamma's
// cot ratio): u*sinc(u) = sin(pi u)/pi exactly by construction,
// and squaring removes the (-1)^n parity from x = n + u.
// v-dd-lead + double-tail, matching the zone's DD evaluation
// shape. Replay: sinc worst 8.874e-19 (target 2^-58).
inline constexpr int kTrigammaSincLead = 3;
inline constexpr int kTrigammaSincNCoef = 6;
inline constexpr double kTrigammaSincLeadHi[3] = {
    0x1.0000000000000p+0, -0x1.a51a6625307d3p+0, 0x1.9f9cb402bc3ebp-1,
};
inline constexpr double kTrigammaSincLeadLo[3] = {
    -0x1.e8dfbd9fab477p-63, 0x1.de8704d0ca72ep-54, 0x1.8f4abb3e3653dp-55,
};
inline constexpr double kTrigammaSincCoef[6] = {
    -0x1.86a8e472088a4p-3, 0x1.ac6805cbe14f0p-6, -0x1.3381697088111p-9, 0x1.37469730d3391p-13, -0x1.d3e3c296a65cfp-18, 0x1.07192db714f81p-22,
};

// Crude tetragamma (psi_2; K=6 asymptotic Bernoulli
// terms, plain double, ~2^-30 relative): ONLY for the
// y.lo * psi_2(y.hi) correction on the reflection path's dd
// argument. Whole correction bounded <= ~2^-55.9 relative
// overall (psi_1 >= 8.93, the negative-axis global min), so
// 2^-30 is ample margin. Replay-measured worst 1.482e-10.
// WALK FORM (G3: mirror this in the kernel): while (y <
// kTrigammaRoughTetraFloor) { s -= 2/(y*y*y); y += 1; } then
// psi_2(y) ~= -(1/y^2 + 1/y^3 + (1/y^2)^2 * Horner(coef, 1/y^2)),
// return s + that (recurrence psi_2(y) = psi_2(y+1) - 2/y^3).
inline constexpr double kTrigammaRoughTetraFloor = 0x1.8000000000000p+2;
inline constexpr int kTrigammaRoughTetraN = 6;
inline constexpr double kTrigammaRoughTetraCoef[6] = {
    0x1.0000000000000p-1, -0x1.5555555555555p-3, 0x1.5555555555555p-3, -0x1.3333333333333p-2, 0x1.aaaaaaaaaaaabp-1, -0x1.a52e52e52e52ep+1,
};

// Deep-tiny guard (0,1)-branch shortcut: below this x, the zone
// term (~pi^2/6 at worst) is < 2^-950 relative of the dd 1/x^2
// term (self-check derivation: e=480 chosen with margin
// over the measured crossover) -- the kernel may return dd(1/x^2)
// alone there. PROBE WARNING (G3): naive double (1/x)^2 or
// 1/(x*x) is NOT reliably correctly-rounded in this regime
// (measured 24-46% 1-ULP misses) -- the reciprocal-square must
// stay dd end-to-end down to the overflow boundary below; if
// Dekker-split limbs land subnormal in this deep-tiny lane, use
// exact power-of-two rescaling (beta's non-FMA subnormal-tau
// reframing pattern, PLAN.md correction 11).
// Overflow boundary (NOTE ONLY, no separate constant): 1/x^2
// itself overflows double below x = 2^-512 = 1/sqrt(DBL_MAX).
inline constexpr double kTrigammaDeepTinyGuard = 0x1.0000000000000p-480;

}  // namespace corvus::detail

#endif  // CORVUS_TRIGAMMA_DATA_H_
